RedisGraph/RedisGraph

- src/Makefile
- src/rmutil/Makefile
- tests/unit/Makefile
> updated makefiles

- demo/bulk_insert/bulk_insert.py
- demo/bulk_insert/requirements.txt
Mostly print(), some encoding issues, and strangely mixed tabs/spaces. Tested to work on both 3.7 and 2.7.
> Python 3 fixes for bulk_import demo.

- src/query_executor.c
> translate merge before naming anonymous nodes

- src/parser/ast.c
- tests/flow/test_query_validation.py
> verify created edge has one relation type

- src/execution_plan/ops/op_delete.c
- src/execution_plan/ops/op_delete.h
- src/graph/edge.h
- src/graph/graph.c
- src/graph/graph.h
- src/graph/node_iterator.c
- src/graph/query_graph.c
- tests/flow/test_graph_deletion.py
- tests/unit/test_graph.cpp
> matrix resize guard by critical section

- src/Makefile
> Use envvar LDFLAGS in linker

- src/arithmetic/algebraic_expression.c
This doesn't fix the newly-opened issue; I just noticed it while digging around!
> Fix re-use of loop index in inner loop

- tests/unit/test_algebraic_expression.cpp
- tests/unit/test_arithmetic_expression.cpp
- tests/unit/test_datablock.cpp
- tests/unit/test_tuples_iter.cpp
I'm going to separate out different fixes into different PRs for simpler reviewing!
> Leak fixes 1

- src/algorithms/all_paths.c
- src/algorithms/all_paths.h
- src/arithmetic/algebraic_expression.c
- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_cond_var_len_traverse.h
- src/graph/graph.c
- tests/unit/test_all_paths.cpp
> Enable variable length path to traverse backwards

- src/graph/graph_type.c
This resolves #191 by introducing persistence for boolean SIValues.
> Support serialization of boolean properties

- demo/bulk_insert/bulk_insert.py
- src/bulk_insert/bulk_insert.c
- src/bulk_insert/bulk_insert.h
- src/commands/cmd_bulk_insert.c
- src/commands/cmd_delete.c
- src/commands/cmd_explain.c
- src/commands/cmd_query.c
- src/graph/graph.c
- src/graph/graph.h
- src/graph/graphcontext.c
- src/graph/graphcontext.h
- src/graph/serializers/graphcontext_type.c
- tests/flow/test_bulk_insertion.py
- tests/flow/test_multi_pattern.py
- tests/unit/test_algebraic_expression.cpp
- tests/unit/test_all_paths.cpp
- tests/unit/test_graph.cpp
- tests/unit/test_index.cpp
> Bulk insert no reallocs

- src/arithmetic/agg_funcs.c
- tests/unit/test_aggregate_functions.cpp
> Verify that argument is valid for aggregate count op

- docs/index.md
Pretty much the suggestion you made! I think 350 looks appropriate, but feel free to play around.
> Logo scales to maximum width of 350px

- mkdocs.yml
Both of these formats work for me locally, but hopefully this will fix the Circle server?
https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
> List Markdown extension features in separate lines

- demo/social/social_queries.py
- docs/commands.md
- src/arithmetic/algebraic_expression.c
- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression.h
- src/graph/serializers/serialize_graph.c
- src/index/index.c
- src/parser/ast_arithmetic_expression.c
- src/parser/grammar.c
- src/parser/grammar.y
- src/parser/lex.yy.c
- src/query_executor.c
- src/resultset/resultset_record.c
- src/value.c
- src/value.h
- tests/flow/test_social.py
- tests/unit/test_algebraic_expression.cpp
- tests/unit/test_arithmetic_expression.cpp
- tests/unit/test_filter_tree.cpp
- tests/unit/test_index.cpp
- tests/unit/test_resultset_record.cpp
- tests/unit/test_value.cpp
Nothing fancy here! Just adding a TYPE function (name from openCypher) to match the newly-added LABELS function.
> Add TYPE function to match LABELS

- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_create.c
- src/execution_plan/ops/op_unwind.c
- src/execution_plan/ops/op_unwind.h
- src/execution_plan/ops/ops.h
- src/parser/ast.c
- src/parser/ast.h
- src/parser/ast_arithmetic_expression.c
- src/parser/clauses/clauses.h
- src/parser/clauses/match.c
- src/parser/clauses/match.h
- src/parser/clauses/unwind.c
- src/parser/clauses/unwind.h
- src/parser/grammar.c
- src/parser/grammar.h
- src/parser/grammar.y
- src/parser/lex.yy.c
- src/parser/lexer.l
- src/query_executor.c
GRAPH.QUERY G "unwind [1,2,3] as v create (a:person)"
> initial support for unwind clause

- src/execution_plan/ops/op.c
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_all_node_scan.c
- src/execution_plan/ops/op_cartesian_product.c
- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_filter.c
- src/execution_plan/ops/op_index_scan.c
- tests/flow/test_multi_pattern.py
> reset should propagate to child ops

- src/graph/serializers/serialize_store.c
Resolves #263 
Previously, when deserializing the properties triemap of a store, we would NULL-terminate the string upon loading it, then insert all strings at once. The heap-allocated returns from `RedisModule_LoadStringBuffer` don't guarantee enough space for that NULL byte, so it can be overwritten by a subsequent load (strings packed directly against each other).
The solution here is to insert each string into the triemap as soon as it is loaded. I've switched to `TrieMap_Add` so that we can skip adding the NULL terminator (and one call to strlen) entirely.
```
(gdb) p propStrings[0]
$1 = 0x6416788 "relation"
(gdb) n
[another property is loaded]
(gdb) p propStrings[0]
$2 = 0x6416788 "relationid"
(gdb) p propStrings[1]
$3 = 0x6416790 "id"
```
> Loaded triemap strings are not guaranteed space for a null terminator

- src/execution_plan/ops/op_conditional_traverse.c
- tests/flow/test_reversed_patterns.py
> queried the wrong operand to see if an algebric expression is reversed

- tests/flow/test_index_scans.py
> Add test for reused index scans under Cartesian products

- src/graph/serializers/serialize_graph.c
- tests/flow/test_persistency.py
> Save the edge count from matrix rather than datablock values

- src/commands/cmd_query.c
Certain Redis server versions do not allow NULL contexts to be used for string management commands (`RedisModule_RetainString`, RedisModule_StringFromString`). This contradicts the Redis module API documentation, but it's at least easy for us to work around.
That said, I'm somewhat tempted to just convert the RedisModuleString to a plain C string and store it that way. We'd need to rebuild the RedisModuleString to open the GraphContext key, but I don't know - it might be less subject to version discrepancies!
Thoughts?
> Use Redis memory manager to store graph name

- src/graph/graphcontext.c
Resolves bug discovered by @gkorland
> Don't attempt index creation on non-existent properties

- src/graph/serializers/serialize_schema.c
- src/parser/ast.c
- src/parser/ast_arithmetic_expression.c
- src/parser/clauses/unwind.c
- src/schema/schema.c
- src/util/triemap/triemap.c
- src/util/triemap/triemap.h
> Remove no-op replace routine from triemaps

- deps/xxhash/.gitattributes
- deps/xxhash/.gitignore
- deps/xxhash/.travis.yml
- deps/xxhash/LICENSE
- deps/xxhash/Makefile
- deps/xxhash/README.md
- deps/xxhash/appveyor.yml
- deps/xxhash/cmake_unofficial/.gitignore
- deps/xxhash/cmake_unofficial/CMakeLists.txt
- deps/xxhash/cmake_unofficial/README.md
- deps/xxhash/doc/xxhash_spec.md
- deps/xxhash/xxhash.c
- deps/xxhash/xxhash.h
- deps/xxhash/xxhsum.1
- deps/xxhash/xxhsum.1.md
- deps/xxhash/xxhsum.c
- src/Makefile
- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_distinct.c
- src/execution_plan/ops/op_distinct.h
- src/execution_plan/ops/ops.h
- src/execution_plan/record.c
- src/execution_plan/record.h
- src/graph/entities/graph_entity.h
- src/resultset/resultset.c
- src/resultset/resultset.h
- tests/flow/redis_base.py
- tests/flow/test_distinct.py
- tests/unit/Makefile
- Introduced xxhash library
- Added Record_Hash64 function
- Implemented OpDistinct
> RETURN DISTINCT execution plan operation (#359)

- src/parser/grammar.c
- src/parser/grammar.y
- src/parser/lex.yy.c
- src/util/datablock/datablock.c
- src/util/datablock/datablock.h
- src/util/datablock/datablock_iterator.h
- src/util/triemap/triemap.h
- src/value.h
> compile on alpine

- docs/commands.md
> Ensure all relation examples are directed

- src/module.c
Allow graph commands from Lua, as Lua issues were resolved by #352.
> Remove deny-script flag from GRAPH commands

- src/arithmetic/algebraic_expression.c
- src/graph/entities/edge.c
- src/graph/entities/edge.h
- src/graph/graph.h
- src/graph/query_graph.c
> delay matrix retrieval, avoid performing matrix sync when possible

- src/arithmetic/arithmetic_expression.c
- src/value.c
- tests/unit/test_arithmetic_expression.cpp
> null plus x returns null

- src/execution_plan/optimizations/reduce_count.c
> node count 0 when label does not exists

- docs/cypher_support.md
- src/parser/grammar.c
- src/parser/grammar.y
> function invocation without arguments

- src/execution_plan/ops/op_cond_var_len_traverse.c
> quick return if there are no relations to traverse

- src/commands/cmd_explain.c
- src/commands/cmd_query.c
> handle empty query

- src/algorithms/all_paths.c
- src/algorithms/all_paths.h
- src/algorithms/path.c
- src/algorithms/path.h
- src/execution_plan/ops/op_cond_var_len_traverse.c
- Fix memory leak
- Reuse buffers in AllPathsCtx
- Don't unnecessarily clone paths
> Improve memory management of All Paths algorithm

- src/commands/cmd_explain.c
> graph.explain runs on a dedicated thread

- src/commands/cmd_bulk_insert.c
- src/commands/cmd_explain.c
- src/commands/cmd_query.c
- src/graph/graphcontext.c
- src/graph/graphcontext.h
- src/module.c
- tests/flow/test_multi_exec.py
added read-write modifiers for Redis key access in graph query
> added read-write modifiers for redis key accsess in graph query

- src/arithmetic/algebraic_expression.c
- tests/unit/test_algebraic_expression.cpp
> split algebraic expression on highly connected nodes

- src/resultset/formatters/resultset_replycompact.c
- tests/tck/features/CreateAcceptance.feature
- tests/tck/features/DeleteAcceptance.feature
- tests/tck/features/FunctionsAcceptance.feature
- tests/tck/features/Literals.feature
- tests/tck/features/MatchAcceptance.feature
- tests/tck/features/MatchAcceptance2.feature
- tests/tck/features/NullAcceptance.feature
- tests/tck/features/OrderByAcceptance.feature
- tests/tck/features/ReturnAcceptance.feature
- tests/tck/features/ReturnAcceptance2.feature
- tests/tck/features/StartingPointAcceptance.feature
- tests/tck/features/WithAcceptance.feature
- tests/tck/features/steps/Steps.py
- tests/tck/utils/assertions.py
enabled TCK testing framework to the new result set structure
> Fix tck framework

- demo/imdb/imdb_queries.py
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_value_hash_join.c
- src/execution_plan/ops/op_value_hash_join.h
- src/execution_plan/ops/ops.h
- src/execution_plan/optimizations/apply_join.c
- src/execution_plan/optimizations/apply_join.h
- src/execution_plan/optimizations/optimizations.h
- src/execution_plan/optimizations/optimizer.c
- src/execution_plan/record.c
- src/execution_plan/record.h
- src/value.c
- tests/flow/test_imdb.py
- tests/tck/features/MatchAcceptance2.feature
- tests/tck/features/VarLengthAcceptance.feature
https://twitter.com/deanc/status/1147952826393534465
> optimize cartesian product by reducing to join

- src/module.c
> log GraphBLAS init error reason

- tests/tck/features/Aggregation.feature
- tests/tck/features/AggregationAcceptance.feature
- tests/tck/features/Comparability.feature
- tests/tck/features/ComparisonOperatorAcceptance.feature
- tests/tck/features/Create.feature
- tests/tck/features/CreateAcceptance.feature
- tests/tck/features/DeleteAcceptance.feature
- tests/tck/features/EqualsAcceptance.feature
- tests/tck/features/FunctionsAcceptance.feature
- tests/tck/features/LargeIntegerEquality.feature
- tests/tck/features/MatchAcceptance.feature
- tests/tck/features/MatchAcceptance2.feature
- tests/tck/features/MergeIntoAcceptance.feature
- tests/tck/features/OrderByAcceptance.feature
- tests/tck/features/StartingPointAcceptance.feature
- tests/tck/features/VarLengthAcceptance.feature
- tests/tck/features/WithAcceptance.feature
- tests/tck/features/steps/Steps.py
- tests/tck/utils/assertions.py
Changes to features are just removing our extra lines (ORDER BYs) and bringing us to parity with the head of the TCK.
The important changes are in `steps.py` and `assertions.py`.
> Tck updates

- docs/commands.md
- src/arithmetic/arithmetic_expression.c
- src/arithmetic/funcs.h
- src/graph/graph.c
- tests/flow/test_social.py
> node incoming outgoing degree

- src/ast/ast.c
- src/ast/ast.h
- src/ast/ast_validations.c
- src/execution_plan/execution_plan.c
> Emit validation error when an alias refers to both nodes and edges

- docs/client_spec.md
- docs/clients.md
- docs/index.md
- docs/result_structure.md
- mkdocs.yml
No rush on this!
Clients have been elevated to a dedicated link, and I added a technical page with details for writing a client implementation (long overdue).
> Client documentation updates

- Dockerfile
added GraphBLAS 3 dependencies to the light docker image build flow
> Fix dockerfile to build GraphBLAS 3 deps

- README.md
- docs/index.md
Documentation updates for OS X compilation, as suggested in #653.
> Add instructions for updating OS X compilers

- src/ast/ast_build_filter_tree.c
- tests/flow/test_with_clause.py
Prior to this query we did not constructed filters applied to WITH projections
> build filter tree applied to the with clause

- src/module.c
> restrict forked process to a single GraphBLAS thread

- src/index/index.c
- tests/flow/test_index_scans.py
> Index set separator

- tests/flow/test_distinct.py
No changes to substance here, just making this file (somewhat) more similar to the others!
> Make test_distinct file format better resemble other flow tests

- src/ast/ast_build_reference_map.c
- tests/unit/test_referenced_entities.cpp
> map set expression right hand side

- src/algorithms/detect_cycle.c
Fixes a local unit test error for me.
> Fix access of uninitialized GrB_Info

- src/algorithms/algorithms.h
- src/algorithms/detect_cycle.c
- src/algorithms/dfs.c
- src/algorithms/dfs.h
- src/algorithms/longest_path.c
- src/algorithms/longest_path.h
- src/arithmetic/algebraic_expression.c
- src/module.c
- tests/unit/test_algebraic_expression.cpp
- tests/unit/test_detect_cycle.cpp
- tests/unit/test_dfs.cpp
> generate algebraic expression from cyclic graph

- src/graph/graph.c
> Don't resize if we only need to flush pending ops

- src/ast/enrichment/annotate_projected_named_paths.c
- src/value.c
- tests/flow/test_union.py
> make sure all return clauses are annotated

- src/execution_plan/optimizations/reduce_count.c
- tests/flow/test_optimizations_plan.py
> treat missing relationship edge count as 0

- src/graph/graphcontext.c
- src/graph/graphcontext.h
- src/module.c
- tests/flow/test_rename.py
this PR solves #793  by renaming the saved graph contexted after a graph key is renamed
> rename graph context after renaming key

- src/arithmetic/list_funcs/list_funcs.c
- tests/tck/features/SemanticErrorAcceptance.feature
- tests/tck/features/steps/Steps.py
> range arg validation

- docs/commands.md
- docs/cypher_support.md
- src/arithmetic/numeric_funcs/numeric_funcs.c
- src/ast/ast_build_op_contexts.c
- src/ast/ast_build_op_contexts.h
- src/ast/ast_build_reference_map.c
- src/ast/ast_validations.c
- src/ast/enrichment/annotate_projected_named_paths.c
- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_delete.c
- src/execution_plan/ops/op_delete.h
- src/execution_plan/ops/op_unwind.c
- tests/flow/test_graph_deletion.py
- tests/tck/features/AggregationAcceptance.feature
- tests/tck/features/EqualsAcceptance.feature
- tests/unit/test_arithmetic_expression.cpp
Both UNWIND and DELETE should be operating on Arithmetic expressions,
Consider:
`MATHC p = ()-[]->() UNWIND nodes(p) AS node DELETE node`
`MATHC p = () DELETE nodes(p)[0]`
> Delete elements verification

- src/ast/ast_validations.c
- tests/flow/test_pagerank.py
- tests/flow/test_query_validation.py
- tests/tck/features/SemanticErrorAcceptance.feature
Improve CREATE validations, fixes crash in #817
> Improve bound variable checking in CREATE clauses

- tests/flow/test_concurrent_query.py
As of #820 concurrent rename and write test might suceesed
> fixed rename and write concurrent test

- docs/cypher_support.md
added regex operator as no supported.
@K-Jo, please approve your vision is valid
> changed cypher_support.md

- src/execution_plan/ops/op_unwind.c
#840 
This will become irrelevant now with @DvirDukhan work on an event mechanism for execution-plan operations.
> op_unwind handel double free

- src/execution_plan/ops/op.c
> avoid creating duplications when aliasing modifiers

- src/arithmetic/algebraic_expression.c
- src/arithmetic/algebraic_expression.h
- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_all_node_scan.c
- src/execution_plan/ops/op_all_node_scan.h
- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_expand_into.c
- src/execution_plan/ops/op_merge.c
- src/execution_plan/ops/shared/create_functions.c
- src/graph/graph.c
- tests/flow/test_graph_merge.py
#836 
merge followed by a second merge position us in a write read write situation,
in this case early creation of both iterator and algebraic expressions might be out of sync with data written in the first merge.
> update algebraic expression operands dim as a result of a prev write

- src/arithmetic/algebraic_expression.c
- src/execution_plan/ops/shared/create_functions.c
> addressed PR comments

- src/execution_plan/ops/op_unwind.c
- tests/tck/features/UnwindAcceptance.feature
> unwind should let record determine element type

- docs/commands.md
- docs/cypher_support.md
- src/algorithms/all_paths.c
- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_conditional_traverse.h
- tests/flow/test_bidirectional_traversals.py
- tests/flow/test_relation_patterns.py
- tests/flow/test_variable_length_traversals.py
- tests/tck/features/AggregationAcceptance.feature
- tests/tck/features/CreateAcceptance.feature
- tests/tck/features/MatchAcceptance.feature
- tests/tck/features/MatchAcceptance2.feature
- tests/tck/features/MatchingSelfRelationships.feature
- tests/tck/features/MergeRelationshipAcceptance.feature
- tests/tck/features/WithAcceptance.feature
Introduce support for bidirectional variable-length traversal and fix bug on referenced edges in bidirectional single-hop traversal.
> Bidirectional traversals

- src/execution_plan/execution_plan.c
- src/execution_plan/optimizations/traverse_order.c
> make sure removed operand is diagonal

- src/graph/graph.c
- tests/flow/test_graph_deletion.py
Fix for bug described in #867 .
Credit to @DvirDukhan for proposing this fix!
> Transpose the deletion mask before updating the transposed adjacency matrix

- src/execution_plan/ops/op_cond_var_len_traverse.c
- tests/flow/test_variable_length_traversals.py
removed the non-existing edge check from var_len_traverse
> removed non existing egde check from var_len_traverse

- src/ast/ast.c
- src/commands/cmd_profile.c
- src/commands/cmd_query.c
- src/procedures/proc_ctx.h
this PR mark the execution of writing/modifing procedure call as write queries.
> added procedure call check for AST_ReadOnly

- src/execution_plan/optimizations/utilize_indices.c
- tests/flow/test_path_filter.py
Resolves a bug in which the children ops of a SemiApply are rearranged during the IndexScan placement optimization, causing an assertion failure on stream resolution in SemiApplyInit.
> Preserve order of op's children array when introducing index scans

- src/filter_tree/filter_tree.c
- src/filter_tree/filter_tree.h
- tests/unit/test_filter_tree.cpp
This PR introduces a filter tree clone function. Enabler for #907
> added filter tree clone

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression.h
- src/execution_plan/optimizations/compact_filters.c
- src/execution_plan/optimizations/compact_filters.h
- src/execution_plan/optimizations/optimizations.h
- src/execution_plan/optimizations/optimizer.c
- src/filter_tree/filter_tree.c
- src/filter_tree/filter_tree.h
- src/value.c
- src/value.h
- tests/flow/test_optimizations_plan.py
- tests/unit/test_filter_tree.cpp
This PR adds filter tree compaction.
Closes #680
> added filter tree compaction

- tests/flow/test_concurrent_query.py
Updates logic in flow test that attempts to rename a graph key while writing to the same graph. This test now handles both possible execution orders.
> Handle both possible execution orders in concurrent rename test

- README.md
- docs/clients.md
This PR improve the markdown table formatting for future use, and add a client library i made recently
> Refferencing a RedisGraph javascript client library

- src/util/arr.h
- tests/unit/test_arr.cpp
- tests/unit/test_utils.cpp
arr.h
clone with clone CB
building block for ops clone PRs
enabler for #907
> added arr clone with cb

- src/ast/ast.c
- src/commands/cmd_delete.c
- src/procedures/procedure.c
- src/procedures/procedure.h
- src/query_ctx.c
A few memory leak fixes in Redis key handles and procedure read-only checks.
> Leak fixes

- src/arithmetic/algebraic_expression/algebraic_expression_construction.c
- src/execution_plan/ops/op_delete.c
- tests/flow/test_graph_merge.py
> label matrix should be fetch right before eval

- src/arithmetic/aggregate.c
- src/arithmetic/arithmetic_expression.c
- src/datatypes/array.c
- src/execution_plan/ops/op_procedure_call.c
- src/execution_plan/ops/op_unwind.c
- src/execution_plan/ops/op_update.c
- src/execution_plan/ops/shared/create_functions.c
- src/execution_plan/record.c
- src/filter_tree/filter_tree.c
- src/graph/entities/graph_entity.c
- src/grouping/group.c
- src/resultset/formatters/resultset_replycompact.c
- src/resultset/formatters/resultset_replyverbose.c
- src/value.c
- src/value.h
- tests/unit/test_value.cpp
This PR doesn't introduce any functional change. `SIValue_Free` now accepts an SIValue instead of a pointer, which is a bit more sensible.
> More sensible function signature for SIValue_Free

- src/graph/graph.c
In spite of my tooling being _very doubtful_ about the memory safety of bulk deletion, I am pretty sure that there are no leaks in this area. Still, I updated the comments and some arguments to have parity with the latest GraphBLAS (`GrB_SCMP` is being deprecated in favor of `GrB_COMP`, for example).
Additionally, moved alloc/free of `Thunk` out of loop.
> Minor updates to bulk deletion

- src/execution_plan/ops/op_aggregate.c
- src/grouping/group.c
- src/grouping/group.h
Group logic updates as suggested in https://github.com/RedisGraph/RedisGraph/pull/947#discussion_r382971519
> Update outdated logic for aggregate groups

- src/query_ctx.c
- src/query_ctx.h
This isn't a necessary PR, but I found this addition quite useful for debugging!
> Add debug function to print query

- .circleci/config.yml
- deps/GraphBLAS/README.md
> Re-enable GraphBLAS circle-ci cache

- src/execution_plan/optimizations/utilize_indices.c
- tests/flow/test_index_scans.py
> Fix invalid op sequence when introducing index scans

- .circleci/config.yml
- docs/requirements.txt
- mkdocs.yml
> Adds versioned documentation (#1034)

- .circleci/config.yml
- docs/requirements.txt
- mkdocs.yml
> Adds versioned documentation for 1.2

- .circleci/config.yml
- docs/requirements.txt
- mkdocs.yml
> Adds versioned documentation to 1.0

- docs/commands.md
> added named path example

- src/execution_plan/ops/op_value_hash_join.c
- src/execution_plan/record.c
- src/value.c
- src/value.h
- tests/flow/test_distinct.py
- tests/flow/test_path.py
- tests/tck/features/MatchAcceptance2.feature
- tests/tck/features/PathEquality.feature
Fixes crashes on path comparison and several DISTINCT scenarios, consolidate code pathways for SIValue hashing.
> Add path comparison, streamline hashing logic

- src/execution_plan/ops/op_value_hash_join.c
- src/execution_plan/record.c
- src/value.c
- src/value.h
- tests/flow/test_distinct.py
- tests/flow/test_path.py
- tests/tck/features/MatchAcceptance2.feature
- tests/tck/features/PathEquality.feature
Backport of the bugfix:
https://github.com/RedisGraph/RedisGraph/pull/1056
> 2.0 Add path comparison, streamline hashing logic

- docs/configuration.md
- src/arithmetic/algebraic_expression/algebraic_expression_debug.c
- src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
- src/arithmetic/algebraic_expression/utils.c
- src/arithmetic/algebraic_expression/utils.h
- src/config.c
- src/config.h
- src/graph/graph.c
- src/graph/graph.h
- tests/flow/test_transpose_configurations.py
- tests/unit/test_algebraic_expression.cpp
- tests/unit/test_all_paths.cpp
- tests/unit/test_graph.cpp
Please note this will double the number of relationship matrices, memory implications.
> Transposed relations

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/boolean_funcs/boolean_funcs.c
- src/arithmetic/list_funcs/list_funcs.c
- src/ast/ast.c
- src/ast/ast.h
- src/ast/ast_build_ar_exp.c
- src/ast/ast_build_filter_tree.c
- src/ast/ast_validations.c
- src/ast/cypher_whitelist.c
- src/ast/cypher_whitelist.h
- src/commands/cmd_query.c
- src/execution_plan/ops/op_create.c
- src/execution_plan/ops/op_delete.c
- src/execution_plan/ops/op_merge_create.c
- src/execution_plan/ops/op_unwind.c
- src/execution_plan/ops/op_update.c
- src/procedures/proc_fulltext_query.c
- src/query_ctx.c
- src/query_ctx.h
> removed RedisModule_ReplyWithError from ast validations

- src/serializers/encoder/v7/encode_graph.c
- tests/flow/test_v7_encode_decode.py
This PR validates that all the states of RDB encoding are encoded properly.
> validate graph schema is encoded

- docs/design.md
* fix graph creation example
* fixed errors in example
`git cherry-pick b8de805`
> fix graph creation example (#1171)

- tests/memcheck.sh
(cherry picked from commit 135e0bc0598d71132e70c810c73bc1b037a5c205)
> make memcheck rule prints full log for files with leaks (#1072)

- src/ast/ast_validations.c
- src/execution_plan/execution_plan.c
- tests/flow/test_union.py
* Improve scoping rules in validating UNION queries
* Bugfix in uniquing column containing both nodes and edges
* Add flow tests
* PR fixes
* PR fixes
(cherry picked from commit a128a0116a1e6df33c2e06f5974bba6fbb997b31)
> Union bugfixes (#1052)

- src/ast/ast_build_filter_tree.c
- tests/unit/test_filter_tree.cpp
(cherry picked from commit b56f98aca71d8ae30addbc70fb2d40b37c7c7ddf)
> Guarantee that NOT conditions are unary (#1092)

- docs/index.md
Please hold back merging this PR.  Thanks
> Adding redis cloud pro to quick start

- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_conditional_traverse.h
- src/execution_plan/ops/op_expand_into.c
- src/execution_plan/ops/op_expand_into.h
- src/execution_plan/ops/shared/traverse_functions.c
- src/execution_plan/ops/shared/traverse_functions.h
- src/execution_plan/optimizations/reduce_count.c
- tests/flow/test_bidirectional_traversals.py
- tests/tck/features/MatchingSelfRelationships.feature
- tests/tck/features/MergeRelationshipAcceptance.feature
* wip
* Remove unnecessary iterator
* WIP
* Fix bidirectional ExpandInto, shared edge populating logic
* PR fixes
* Post-rebase fixes
* Fix PR comments
(cherry picked from commit d46c6b69ff11088f9c5a112087ed7331b29625b9)
> Bidirectional expand into (#1047)

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression.h
- src/ast/ast_build_ar_exp.c
- src/execution_plan/optimizations/seek_by_id.c
- src/execution_plan/optimizations/utilize_indices.c
- tests/flow/test_params.py
* added params support to id seek
* reduce to scalar with runtime
* fixed PR comments
* fixed PR comments
(cherry picked from commit bc609c3b6da1f217986a534a9f032f9b51f0b987)
> added params support to id seek (#1164)

- src/index/index.c
(cherry picked from commit 5293ced4f8bf63974a6d8a99750b3f0701a3587d)
> enable search GC (#1194)

- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
- tests/tck/features/CreateAcceptance.feature
- tests/tck/features/MiscellaneousErrorAcceptance.feature
- tests/tck/features/steps/Steps.py
> Emit compile time error on creation of undirected edges

- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
- tests/tck/features/CreateAcceptance.feature
- tests/tck/features/MiscellaneousErrorAcceptance.feature
- tests/tck/features/steps/Steps.py
(cherry picked from commit 941b1204d81740b1648e0e11d238ac39f05185d3)
> Emit compile time error on creation of undirected edges (#1212)

- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_update.c
- src/execution_plan/ops/op_update.h
- src/graph/entities/node.h
- src/graph/graphcontext.c
- src/index/index.h
- src/schema/schema.c
This PR reduce the number of times we index an updated node
> Update index on change

- .astylerc
This reverts commit e33c5bffffacac9c2ab656e5f4067c1f0836c2c2.
> Revert "line length 80 (#1227)"

- src/execution_plan/ops/op_apply.c
- src/execution_plan/ops/op_value_hash_join.c
- src/execution_plan/record.c
- src/execution_plan/record.h
- tests/flow/test_hashjoin.py
Fix #1124 
I believe Record merge is dangerous, there's no validation on the record length, also what if the records have different mapping?
> clone cached record before mergeing

- src/Makefile
- src/RG.h
- src/util/datablock/datablock.c
- tests/unit/test_graph.cpp
Use `ASSERT(exp)` to evaluate and assert expression only in debug mode, in release the expression and assertion are removed.
> debug assertion

- docs/commands.md
- docs/cypher_support.md
- src/arithmetic/comprehension_funcs/comprehension_funcs.c
- src/ast/ast_build_ar_exp.c
- src/ast/ast_build_filter_tree.c
- src/ast/ast_validations.c
- src/ast/cypher_whitelist.c
- src/filter_tree/filter_tree.c
- tests/flow/test_comprehension_functions.py
> Any all comprehensions

- docs/commands.md
Adds documentation for the GRAPH.PROFILE entrypoint, resolving #1292
> Document GRAPH.PROFILE entrypoint

- docs/configuration.md
> added CACHE_SIZE docs

- tests/flow/test_params.py
> update parser to support negative values

- src/arithmetic/conditional_funcs/conditional_funcs.c
- tests/flow/test_function_calls.py
> CASE...WHEN should only accept truthy values

- docs/cypher_support.md
this is obvious since maps as a type are not supported, but it doesn't hurt to be explicit.
> mention properties function is not supported

- docs/commands.md
(cherry picked from commit 5e8bac62a770106b75e979aa089ee558a0a50993)
> Document GRAPH.PROFILE entrypoint (#1294)

- src/bulk_insert/bulk_insert.c
Module-side changes to support loading array properties.
> Support array properties in bulk loader

- docs/bulk_spec.md
- docs/index.md
- mkdocs.yml
> Add GRAPH.BULK documentation and link to bulk loader documentation

- deps/GraphBLAS/README.md
- src/arithmetic/func_desc.c
- src/arithmetic/repository.c
- src/arithmetic/string_funcs/string_funcs.c
- src/procedures/procedure.c
- src/procedures/procedure.h
- src/util/strutil.c
- src/util/strutil.h
- tests/flow/test_procedures.py
> Allow upper case letters in proc names

- README.md
- docs/index.md
* reaplace gitter with Discord
* replace gitter to discord
(cherry picked from commit f7ab13b30a18a2c239aaf96332ee776ba1ebfc28)
> replace gitter with Discord (#1395)

- src/module_event_handlers.c
- src/util/thpool/thpool.c
[emutechnology](https://www.emutechnology.com/) require `GrB_finalize` to be called in order to properly shut down their system
> Handle shutdown

- src/arithmetic/algebraic_expression/algebraic_expression_construction.c
- src/arithmetic/algebraic_expression/algebraic_expression_eval.c
- src/arithmetic/entity_funcs/entity_funcs.c
- src/ast/ast.c
- src/ast/ast_build_op_contexts.c
- src/ast/ast_validations.c
- src/commands/cmd_profile.c
- src/commands/cmd_query.c
- src/execution_plan/execution_plan.c
- src/execution_plan/execution_plan_build/build_projection_ops.c
- src/execution_plan/ops/op_apply_multiplexer.c
- src/execution_plan/ops/op_filter.c
- src/execution_plan/ops/op_semi_apply.c
- src/execution_plan/ops/op_update.c
- src/execution_plan/ops/shared/create_functions.c
- src/execution_plan/optimizations/utilize_indices.c
- src/graph/entities/qg_node.c
- src/index/index.c
- src/serializers/decoders/prev/v4/decode_graph.c
- src/serializers/encoder/v8/encode_graph_entities.c
Fix the warnings reported by #1413 that are not false positives or not otherwise desirable.
@filipecosta90 FWIW, I didn't find this report terribly useful - do we really want to incorporate this into our CI?
> Fix warnings reported by fb-infer

- src/execution_plan/ops/shared/create_functions.c
Addresses the comment at https://github.com/RedisGraph/RedisGraph/pull/1440#discussion_r526645739
> Delete redundant check to create edge schemas

- docs/commands.md
> Document dbms.procedures()

- docs/clients.md
New php client redislabs-redisgraph-php added to the available clients list.
> new php client redislabs-redisgraph-php added

- docs/clients.md
* Add stars to clients
* Update clients.md
(cherry picked from commit b3e422213dbb5e35c751c5701337c533e38cfcc6)
> Add stars to clients (#1462)

- src/ast/ast.c
- src/ast/ast.h
- src/ast/ast_validations.c
- src/execution_plan/execution_plan.c
- tests/flow/test_query_validation.py
- tests/unit/test_aggregate_functions.cpp
- tests/unit/test_arithmetic_expression.cpp
> validate clauses following a RETURN clause

- src/arithmetic/arithmetic_expression.c
- src/bulk_insert/bulk_insert.c
- src/execution_plan/optimizations/reduce_traversal.c
- src/procedures/proc_bfs.c
- src/procedures/proc_fulltext_query.c
- src/procedures/proc_labels.c
- src/procedures/proc_pagerank.c
- src/procedures/proc_procedures.c
- src/procedures/proc_property_keys.c
- src/procedures/proc_relations.c
- src/serializers/encoder/v8/encode_graph.c
- src/value.c
resolve a number of clang warnings
> warnings fixes

- src/execution_plan/ops/op_update.c
- src/graph/entities/graph_entity.c
- src/graph/entities/graph_entity.h
- src/graph/graph.c
- src/graph/graph.h
- src/util/datablock/datablock.c
- src/util/datablock/datablock.h
- tests/flow/test_graph_deletion.py
> Disallow updating properties after deleting their entities

- src/execution_plan/optimizations/traverse_order.c
- tests/flow/test_relation_patterns.py
- tests/unit/test_traversal_ordering.cpp
This PR improves the logic of selecting an AlgebraicExpression starting point such that both labels and filters are considered in finding the optimal start.
> Consider both filters and labels in selecting a starting point

- src/arithmetic/algebraic_expression/algebraic_expression.c
- src/arithmetic/algebraic_expression/utils.c
- src/execution_plan/ops/op_cond_var_len_traverse.c
- tests/flow/test_relation_patterns.py
> optimize expression before accessing it

- ramp.yml
> disable runtime config on enterprise

- README.md
- docs/clients.md
Updating 'redis-modules-sdk' inside README and adding to clients.md
> Updating 'redis-modules-sdk' inside README and adding to clients.md

- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_create.c
- tests/flow/test_graph_create.py
> Persist Record values before storing them in OpCreate

- src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
- tests/flow/test_bidirectional_traversals.py
- tests/flow/test_bulk_insertion.py
- tests/flow/test_relation_patterns.py
- tests/unit/test_algebraic_expression.cpp
> wrongly assumed add op had only 2 operands

- docs/commands.md
- src/arithmetic/numeric_funcs/numeric_funcs.c
- tests/tck/features/expressions/mathematical/Mathematical13.feature
- tests/unit/test_arithmetic_expression.cpp
> add sqrt function

- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
> multiple use for rax in proc call validation

- src/execution_plan/ops/op.c
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_distinct.c
- src/execution_plan/ops/op_distinct.h
- src/execution_plan/record.c
- src/execution_plan/record.h
- tests/flow/test_distinct.py
> compute distinct hash only on projected values

- src/bulk_insert/bulk_insert.c
- src/commands/cmd_bulk_insert.c
when performing bulk insert, make sure graph sync policy is set to resize only
> set graph sync policy to resize only

- src/util/json_encoder.c
- tests/flow/test_function_calls.py
https://github.com/RedisGraph/RedisGraph/issues/1722
> Fixed bug in JsonEncoder: invalid cast bug: #1722

- Dockerfile
> apt update on debian derivitives only

- .circleci/config.yml
access to the variables in the organization context
> circleci context

- docs/commands.md
> Add documentation for startNode() and endNode()

- src/datatypes/array.c
- src/datatypes/map.c
- src/execution_plan/ops/op_aggregate.c
- src/grouping/group.c
- src/grouping/group.h
- src/grouping/group_cache.c
- src/grouping/group_cache.h
- src/value.c
- src/value.h
issue: Wrong group association #1651
> fixed aggregate ambigous grouping.

- .circleci/config.yml
- sbin/system-setup.py
updating to the latest redis docker
> fix psbuilt distutils issue

- .circleci/config.yml
- sbin/pack.sh
- sbin/system-setup.py
- src/Makefile
* Fix packaging for CentOS8
* fixes 1
* fixes 2
* fixes 3
* fixes 4
* fixes 5
* fixes 6
> Cherry-pick Fix packaging for CentOS8 (#1823)

- src/graph/graph.c
I think we should always maintain transposed matrices, otherwise our performance are going down the drain
> use the transposed relationship type matrix when collecting edges

- src/arithmetic/list_funcs/list_funcs.c
- tests/tck/features/expressions/list/List11.feature
When range 
RETURN range(0, -123) AS list
also implement range correctly and enable TCK tests
> Fix crash of range func

- src/graph/graph.c
- src/graph/rg_matrix/rg_new.c
- src/graph/rg_matrix/rg_remove_element.c
- src/graph/rg_matrix/rg_remove_entry.c
- src/graph/rg_matrix/rg_set_element_uint64.c
- src/index/index.c
- src/procedures/proc_bfs.c
- tests/unit/test_rg_matrix.cpp
RG_Matrix transpose matrix converted to bool matrix to reduce memory size
> convert transposed matrix to bool

- .circleci/config.yml
> Refresh GraphBLAS cache

- .circleci/config.yml
- sbin/system-setup.py
> Fixing permissions for OSX peg install

- docs/commands.md
> Update endpoint documentation with reference to timeout arg

- .circleci/config.yml
- src/arithmetic/conditional_funcs/conditional_funcs.c
- tests/unit/test_arithmetic_expression.cpp
fixes https://github.com/RedisGraph/RedisGraph/issues/1874
> fix case null

- src/commands/cmd_query.c
- src/execution_plan/execution_plan.c
- src/execution_plan/execution_plan.h
- src/util/cron.c
- src/util/cron.h
- tests/unit/test_cron.cpp
> cron task abort [WIP]

- src/commands/cmd_config.c
- src/configuration/config.c
- tests/flow/test_config.py
Resolves comments made on #1904
> Address PR comments

- tests/flow/test_timeout.py
Additional testing for handing query timeout
> timeout different scans

- docs/References.md
- docs/clients.md
- docs/commands.md
- docs/index.md
> Update links in docs to point to redis.com

- docs/clients.md
> Replaces "Redis Labs" with "Redis".

- docs/commands.md
- src/arithmetic/string_funcs/string_funcs.c
- src/arithmetic/string_funcs/string_funcs.h
- tests/unit/test_arithmetic_expression.cpp
implement replace function https://github.com/RedisGraph/RedisGraph/issues/1965
> String funcs

- src/graph/query_graph.c
- tests/flow/test_multi_label.py
fixes https://github.com/RedisGraph/RedisGraph/issues/1999
> update label for every node in ast

- tests/memcheck.sh
* Memcheck script only checks for server-process leaks
* Address PR comments
(cherry picked from commit 4a72eb1dedcb166d8d448c5723ceff0968d2d959)
> Memcheck script only checks for server-process leaks (#1934)

- src/execution_plan/optimizations/traverse_order_utils.c
- tests/flow/test_traversal_construction.py
Resolves #2005 and enables LDBC test interactive-complex-11.
> Fix evaluation of variable-length edges in expression ordering

- src/arithmetic/numeric_funcs/numeric_funcs.c
- src/errors.c
- src/errors.h
- tests/flow/test_function_calls.py
> modulo by zero should emit division by zero error

- docs/commands.md
- src/arithmetic/arithmetic_expression_construct.c
- src/arithmetic/comprehension_funcs/comprehension_funcs.c
- src/arithmetic/func_desc.c
- src/arithmetic/list_funcs/list_funcs.c
- src/arithmetic/list_funcs/list_funcs.h
- src/ast/ast_validations.c
- src/ast/cypher_whitelist.c
- tests/flow/test_bfs.py
- tests/flow/test_reduce.py
Support for the `reduce` function
> reduce function

- src/graph/graph.c
- tests/flow/test_concurrent_query.py
RWLock should favor write
#1588
> Favor write lock

- src/filter_tree/ft_to_rsq.c
- tests/flow/test_index_scans.py
> switch to new RediSearch API

- docs/configuration.md
> Document how to set run-time configurations

- .circleci/config.yml
- tests/fuzz/requirements.txt
- tests/requirements.txt
Fixes the dependencies of the fuzzer so that the CI job runs again.
> Install Python dependencies in fuzzer job

- src/ast/ast_validations.c
- src/execution_plan/execution_plan_build/execution_plan_construct.c
- src/execution_plan/ops/op_delete.c
- tests/flow/test_graph_deletion.py
> Add compile-time and run-time validations for DELETE

- src/graph/graph.c
- tests/flow/test_graph_deletion.py
> Correctly skip already-deleted edges when enqueuing deletions

- .circleci/config.yml
Addresses: https://app.circleci.com/pipelines/github/RedisGraph/RedisGraph/5758/workflows/39d20700-8582-4259-8352-b137cd05bde5/jobs/22555
> Disable CI profilers until overhead is solved

- src/arithmetic/list_funcs/list_funcs.c
- src/ast/ast.c
- src/ast/ast_shared.c
- src/commands/execution_ctx.c
- src/execution_plan/execution_plan.c
- src/execution_plan/execution_plan.h
- src/execution_plan/ops/op_delete.c
- src/index/index.c
- src/schema/schema.c
- tests/Makefile
- tests/flow/Makefile
- tests/flow/test_config.py
- tests/flow/test_graph_create.py
Fix memcheck job for flow tests and various memory leaks.
> Expect valgrind failure

- src/commands/execution_ctx.c
- tests/flow/test_query_validation.py
fixes https://github.com/RedisGraph/RedisGraph/issues/2282
> fix empty query

- src/arithmetic/aggregate_funcs/agg_funcs.c
- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression.h
- src/arithmetic/arithmetic_expression_construct.c
- src/arithmetic/boolean_funcs/boolean_funcs.c
- src/arithmetic/comprehension_funcs/comprehension_funcs.c
- src/arithmetic/conditional_funcs/conditional_funcs.c
- src/arithmetic/entity_funcs/entity_funcs.c
- src/arithmetic/func_desc.c
- src/arithmetic/func_desc.h
- src/arithmetic/list_funcs/list_funcs.c
- src/arithmetic/map_funcs/map_funcs.c
- src/arithmetic/numeric_funcs/numeric_funcs.c
- src/arithmetic/path_funcs/path_funcs.c
- src/arithmetic/placeholder_funcs/placeholder_funcs.c
- src/arithmetic/point_funcs/point_funcs.c
- src/arithmetic/string_funcs/string_funcs.c
- src/arithmetic/time_funcs/time_funcs.c
- src/ast/ast_build_filter_tree.c
- src/commands/execution_ctx.c
- src/execution_plan/execution_plan_build/build_pattern_comprehension_ops.c
- src/execution_plan/optimizations/utilize_indices.c
- src/filter_tree/filter_tree.c
- tests/flow/test_query_validation.py
- tests/unit/test_aggregate_functions.cpp
fixes https://github.com/RedisGraph/RedisGraph/issues/2299
> hide internal functions

- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
fixes https://github.com/RedisGraph/RedisGraph/issues/2312
> validate function calls in merge clase

- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
fixes https://github.com/RedisGraph/RedisGraph/issues/2321
> validate function calls in merge actions

- src/filter_tree/ft_to_rsq.c
- tests/flow/test_index_scans.py
fixes https://github.com/RedisGraph/RedisGraph/issues/2348
> fix crash converting filter tree to redisearch query

- src/graph/graph.c
- src/graph/graph.h
- tests/flow/test_multi_label.py
- tests/unit/test_graph.cpp
fixes https://github.com/RedisGraph/RedisGraph/issues/2357
https://github.com/RedisGraph/RedisGraph/issues/2361
> fix node label deletion

- src/graph/graph.c
- tests/flow/test_graph_deletion.py
regression of undo log PR https://github.com/RedisGraph/RedisGraph/pull/2116
> fix self edge deletion counter

- src/arithmetic/arithmetic_expression.c
- src/filter_tree/ft_to_rsq.c
- src/index/index.c
- tests/flow/test_index_scans.py
- tests/fuzz/Makefile
fixes:
https://github.com/RedisGraph/RedisGraph/issues/2393
https://github.com/RedisGraph/RedisGraph/issues/2395
> fix crashes in index search

- src/arithmetic/string_funcs/string_funcs.c
- tests/flow/test_function_calls.py
> Verify subsrting allocated length doesn't overflow

- docs/docs/configuration.md
- src/util/json_encoder.c
- tests/flow/test_function_calls.py
> Add support for toJSON of point

- src/value.c
- tests/flow/test_function_calls.py
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=30484
> fix #2377 add solution for -INF%-1

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression.h
- src/arithmetic/string_funcs/string_funcs.c
- src/filter_tree/ft_to_rsq.c
- tests/flow/test_index_scans.py
> add tests for index search

- src/value.c
- tests/flow/test_function_calls.py
fixes: https://github.com/RedisGraph/RedisGraph/issues/2407
> fix crash in double to string

- README.md
> Fixing install docs for ubuntu

- src/util/json_encoder.c
- tests/flow/test_function_calls.py
fix https://github.com/RedisGraph/RedisGraph/issues/2420
> fix torsion double precision

- src/graph/graphcontext.c
- tests/flow/test_index_create.py
fix https://github.com/RedisGraph/RedisGraph/issues/2394
> fix crash on free index

- src/graph/graph_hub.c
- src/undo_log/undo_log.c
- src/undo_log/undo_log.h
- tests/flow/test_undo_log.py
This PR adds the undo log for `REMOVE` and `SET` labels
> undo log for label add and remove

- docs/commands/graph.query.md
> Update graph.query.md - paths

- tests/flow/test_multi_pattern.py
fix https://github.com/RedisGraph/RedisGraph/issues/2491
> fix missing space issue

- docs/commands/graph.query.md
- docs/docs/cypher_support.md
- src/arithmetic/boolean_funcs/boolean_funcs.c
- tests/flow/test_function_calls.py
- wordlist
This PR adds the support for `toBooleanOrNull`
> toBooleanOrNull

- .circleci/config.yml
- sbin/system-setup.py
- sbin/upload-artifacts
* Fix S3 upload mechanism: getaws
* fix 1
* fix 2
Co-authored-by: Avi Avni <avi.avni@gmail.com>
(cherry picked from commit 37e271279dd071e81f2ef61fe1382139849c7124)
> [2.10] Fix S3 upload mechanism: getaws (#2510)

- src/arithmetic/list_funcs/list_funcs.c
- tests/flow/test_reduce.py
fix https://github.com/RedisGraph/RedisGraph/issues/2517
> fix crash in reduce

- src/ast/ast.c
- tests/flow/test_profile.py
- tests/flow/test_query_validation.py
- tests/unit/test_referenced_entities.cpp
fix https://github.com/RedisGraph/RedisGraph/issues/2467
> change anon alias cannot be created by user

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/entity_funcs/entity_funcs.c
- src/datatypes/point.c
- src/datatypes/point.h
- src/value.c
- tests/flow/test_point.py
This PR is to solve issue #2477 
Of course, any comments and suggestions are welcome!
Thanks
> Extract latitude or longitude of a point

- docs/commands/graph.query.md
- docs/docs/cypher_support.md
- src/arithmetic/numeric_funcs/numeric_funcs.c
- tests/flow/test_function_calls.py
adds the support for `toFloatOrNull` function.
> toFloatOrNull

- docs/commands/graph.query.md
- docs/docs/cypher_support.md
- src/arithmetic/numeric_funcs/numeric_funcs.c
- tests/flow/test_function_calls.py
adds `toIntegerOrNull` support
> toIntegerOrNull

- src/index/index_edge.c
- tests/flow/test_edge_index_scans.py
fix https://github.com/RedisGraph/RedisGraph/issues/2558
> fix multi edge index

- src/arithmetic/aggregate_funcs/agg_max.c
- src/arithmetic/aggregate_funcs/agg_min.c
- tests/flow/test_function_calls.py
fix https://github.com/RedisGraph/RedisGraph/issues/2571
> fix min and max clone aggregated value

- src/execution_plan/optimizations/utilize_indices.c
- tests/flow/test_index_scans.py
fix https://github.com/RedisGraph/RedisGraph/issues/2591
> fix utilize index scan

- docs/commands/graph.query.md
- src/arithmetic/boolean_funcs/boolean_funcs.c
- src/arithmetic/comprehension_funcs/comprehension_funcs.c
- tests/flow/test_function_calls.py
Hi, this PR implements #2649. 
Comments are welcome.
Thanks
> Support isEmpty()

- src/ast/ast_build_reference_map.c
- tests/flow/test_bound_variables.py
fix https://github.com/RedisGraph/RedisGraph/issues/2687, https://github.com/RedisGraph/RedisGraph/issues/2414
> add reference entities in unwind

- src/execution_plan/ops/op.c
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_all_node_scan.c
- src/execution_plan/ops/op_node_by_id_seek.c
- src/execution_plan/ops/op_node_by_label_scan.c
- src/execution_plan/record.c
- src/execution_plan/record.h
- tests/flow/test_graph_merge.py
fix https://redislabs.atlassian.net/browse/MOD-4286
> fix crash using freed values

- tests/flow/test_params.py
- tests/flow/test_reduce.py
- tests/tck/features/clauses/match-where/MatchWhere2.feature
- tests/tck/features/clauses/with-where/WithWhere2.feature
fix https://github.com/RedisGraph/RedisGraph/issues/2460
> remove old parameter syntax

- src/filter_tree/filter_tree.c
- tests/flow/test_aggregation.py
fix https://github.com/RedisGraph/RedisGraph/issues/2497
> fix apply filter comparing null

- .github/wordlist.txt
- README.md
- docs/docs/_index.md
- docs/docs/design/_index.md
- ramp.yml
> license update (#2707)

- src/execution_plan/optimizations/optimize_label_scan.c
- tests/flow/test_optimizations_plan.py
Replacement AlgebraicExpression fixed to original label
> Fix optimize-label-scan

- src/commands/cmd_query.c
- tests/flow/test_timeout.py
Check whether a timeout error has occurred before printing the result set in PROFILE.
Answers #2740.
> timeout fix

- src/execution_plan/ops/shared/create_functions.c
- src/graph/graph_hub.c
- src/graph/graph_hub.h
it improve the perf of creating new nodes and edges
> Inherit attribute set

- src/ast/ast_validations.c
- src/ast/ast_validations.h
> Remove compilation warnings

- deps/GraphBLAS/Config/README.md.in
- deps/GraphBLAS/README.md
- deps/GraphBLAS/Source/GB_Global.c
Disable GraphBLAS memory pool due to performance hit under high contention
> disable memory pool

- src/arithmetic/algebraic_expression/algebraic_expression_construction.c
- src/arithmetic/algebraic_expression/algebraic_expression_mul.c
- src/execution_plan/execution_plan_build/build_match_op_tree.c
- src/graph/entities/qg_edge.c
- src/graph/entities/qg_edge.h
- tests/flow/test_traversal_construction.py
> expand 0 length edge using var len traversal

- src/ast/ast_rewrite_star_projections.c
- tests/flow/test_star_projections.py
fix https://github.com/RedisGraph/RedisGraph/issues/2880
> fix crash in rewrite star projection

- docs/docs/commands.md
Closes https://redislabs.atlassian.net/browse/DXDOCS-281
> [DOC-BUG] Fixes broken link in Graph commands overview

- src/util/simple_timer.h
- src/util/time.c
- src/util/time.h
1. Adds a method to obtain a unix timestamp. This wil be used by the GRAPH.INFO command to show the query receive time.
2. Adds some convenient types and macros to use with the simple timer facility.
> Add some utility functions related to time.

- docs/docs/clients.md
The list of clients in the README should be canonical - updating these to match the README. cc @nermiller
> Updating client library list

- src/execution_plan/ops/op_foreach.c
- src/execution_plan/ops/op_join.c
- tests/flow/test_foreach.py
- tests/flow/test_union.py
This PR is to solve #3038 
The change was done in function ``JoinConsume()``, is the stream is depleted, the reset is propagated to release locks if any exists.
> Fix LockWrite crash

- src/execution_plan/ops/op_node_by_label_scan.c
- src/graph/rg_matrix/rg_matrix_iter.c
- src/util/range/unsigned_range.c
Fix access after free, once an iterator is seek on a modified matrix
> Reattach on reset

- tests/flow/test_timeout.py
> Fix flaky timeout (#3110)

- src/ast/ast_rewrite_call_subquery.c
- tests/flow/test_call_subquery.py
This PR is to solve bug #3138 
The following functions were modified:
``_replace_with_clause()`` and ``_replace_return_clause()``
> Fix star projections in CALL{}

- .circleci/config.yml
- ramp.yml
- src/module.c
See attache Python script, we might want to incorporate it into our work-flow.
[main.txt](https://github.com/RedisGraph/RedisGraph/files/12062441/main.txt)
> require Redis version 6.2.0 or above

- docs/commands/graph.query.md
Fixes the documentation for Call {}.
> Call {} Doc-fix

- src/execution_plan/ops/op.c
- tests/flow/test_graph_merge.py
fix https://github.com/RedisGraph/RedisGraph/issues/3146
> fix crash in propogate reset when function pointer is null

- src/graph/graph.c
- src/graph/graph_hub.c
- tests/flow/test_graph_deletion.py
fix https://github.com/RedisGraph/RedisGraph/issues/3144
> fix delete none existing label

- src/execution_plan/ops/op_merge_create.c
- tests/flow/test_graph_merge.py
fix https://github.com/RedisGraph/RedisGraph/issues/3145
> fix merge create reserve node

- .circleci/config.yml
- src/arithmetic/entity_funcs/entity_funcs.c
- src/ast/ast.c
- src/commands/cmd_constraint.c
- src/commands/cmd_query.c
- src/effects/effects.c
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_delete.c
- src/execution_plan/ops/op_delete.h
- src/execution_plan/ops/shared/update_functions.c
- src/graph/entities/edge.c
- src/graph/entities/edge.h
- src/graph/graph_delete_nodes.c
- src/graph/graph_hub.c
- src/graph/graphcontext.c
- src/graph/rg_matrix/rg_wait.c
- src/query_ctx.c
- src/query_ctx.h
- src/resultset/formatters/resultset_replycompact.c
- src/resultset/formatters/resultset_replyverbose.c
- src/undo_log/undo_log.c
- src/undo_log/undo_log.h
- src/util/json_encoder.c
- tests/benchmarks/explicit_edge_deletion.yml
- tests/benchmarks/implicit_edge_deletion.yml
- tests/flow/test_graph_deletion.py
- tests/tck/features/clauses/merge/Merge5.feature
fixes https://github.com/RedisGraph/RedisGraph/issues/3150, https://github.com/RedisGraph/RedisGraph/issues/2263
> make delete operation eager

- .circleci/config.yml
(cherry picked from commit 446ac5ea5b934fa0724ffad6c998290f7d3e914b)
> Update config.yml - test with Redis 7.2 (#3164)

- src/cron/cron.c
https://github.com/RedisGraph/RedisGraph/issues/3134
> fix cron busy loop

- src/ast/ast_validations.c
- src/serializers/graphcontext_type.c
- tests/flow/test_union.py
fix https://github.com/RedisGraph/RedisGraph/issues/3186
> fix validation regression

- README.md
This adds the mention of a maintained fork, FalkorDB.
> Add mention of Falkor

- src/arithmetic/map_funcs/map_funcs.c
- tests/flow/test_function_calls.py
> Properties function should return a new map
