- docs/commands.md
- docs/design.md
- docs/index.md
there is typo in line 239 in docs/commands.md 
WHEREE instead of WHERE
> typo in commands.md and no closing '}' in python example code

- src/arithmetic/arithmetic_expression.c
- src/bulk_insert.c
- src/execution_plan/ops/op_aggregate.c
- src/graph/graph_type.c
- src/graph/query_graph.c
- src/parser/grammar.c
- src/parser/grammar.y
- src/parser/lex.yy.c
- src/query_executor.c
- src/resultset/record.c
- src/resultset/record.h
- src/resultset/resultset.c
- src/stores/store_type.c
- src/value.c
- src/value.h
- src/value_cmp.c
- tests/unit/Makefile
- tests/unit/test_algebraic_expression.c
- tests/unit/test_arithmetic_expression.c
- tests/unit/test_node.c
- tests/unit/test_resultset_record.c
- tests/unit/test_value.c
This PR replaces the `SIString` member of the `SIValue` union with a `char *`, as (to the best of my knowledge) Redis-Graph only ever uses null-terminated strings.
Making this change reduces the size of the `SIValue` struct from 24 to 16 bytes.
The code contained in this PR has been live on the swilly22/master for a few months, so I don't believe this change should have any negative consequences.
> Sivalue string refactor

- src/graph/graph.c
This is a pretty trivial modification, really, but I like it a bit better than the former delta approach. It has a bit less logical complexity, and it increases the number of blocks by an integer factor on each realloc (the other method would increase the number of blocks by `3x + (number of new blocks required)`)`.
The minimum realloc like this is `2x`, which I think is fine, but we can change that to `3x` to have a smaller change on the scaling factor while still growing by simpler factors.
> Only resize NodeBlock count by integer multiples

- demo/bulk_insert/bulk_insert.py
- src/bulk_insert.c
- tests/flow/test_bulk_insertion.py
This PR corrects the token count logic on large inserts of relations, so that the largest insert buffer possible should always be created without causing Redis to block the query.
It additionally adds some console logging to give the user some knowledge of how far along the process is. The logging is accurate, but a bit rudimentary - every time a buffer is passed to Redis, it prints the entity inserted vs. total counts for the current CSV, as well as the percent completion of that inserted.
This has the potential to get pretty spammy on really large CSVs, and if many different labels and/or relationships are being inserted, it doesn't give much context on how far along the overall creation is.
In order to give overall creation context, we would need to get the line count of all input …
> Bulk insert progress meter

- demo/imdb/requirements.txt
- demo/social/requirements.txt
- src/resultset/resultset.c
- tests/flow/requirements.txt
This breaks once a value contains comma, this commit changes result-set structure to return records and the header row as individual arrays.
> result-set record used to be a single comma delimited string

- src/resultset/resultset.c
- src/rmutil/vector.c
- src/rmutil/vector.h
- src/value.c
- src/value.h
Queries that have an ORDER BY clause and no limit will use a quicksort algorithm to sort result set records.
The `SIValue_Compare` function has better handling of disjoint types, resolving issue #86.
> Implement quicksort for ORDER clauses

- docs/index.md
> Adds a couple of clients

- src/module.c
- src/parser/ast.c
- src/parser/clauses/match.c
- src/parser/clauses/return.c
- src/query_executor.c
- src/query_executor.h
This PR resolves issue #110
The `ModifyAST` function (which for many queries must precede `AST_Validate`) can now construct and return user-facing error messages.
> Strict return validations

- demo/social/social_queries.py
- src/graph/graph.c
- tests/flow/test_social.py
- tests/unit/test_graph.cpp
This PR resolves issue #98. It features two primary changes:
- Simplifications to the swap-and-resize logic for `Graph_DeleteNodes`
- Adding functionality to reset matrices to just their nonzero elements after they are modified.
The second point is really the important one here, as our `TuplesIter` logic does not distinguish between false and true values - it just checks whether that value has been explicitly set or not. I don't really feel like that's a problem at present, and the matrix reset logic makes matrices a lot simpler (and I expect faster within GraphBLAS) in general.
This is not 100% ready to be merged, as matrix simplification here is being lazily performed in tandem with matrix resizing. In the case that a matrix has been modified but does not need to be resized (x nodes …
> Simplify node deletion and reset explicit 0 values in matrices

- src/module.c
@swilly22 I'm pretty sure this change resolves issue #118, which was caused by the ThreadSafeContext lock getting released before `RedisModule_ReplicateVerbatim` was called.
In this fix, I separated the unlock calls so that the module lock is released first, then the context lock is released once the keyspace is synchronized. Does that separation actually benefit us, though? If not, we could just reorder the calls to release all locks after synchronizing the keyspace.
> Release module-scoped write lock and context-scoped lock separately

- demo/imdb/imdb_queries.py
- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression.h
- src/execution_plan/execution_plan.c
- src/execution_plan/optimizations/utilize_indices.c
- src/filter_tree/filter_tree.c
- src/filter_tree/filter_tree.h
- src/index/index.c
- src/index/index.h
- src/parser/ast.c
- src/parser/ast_arithmetic_expression.c
- src/parser/ast_arithmetic_expression.h
- src/parser/clauses/where.c
- src/parser/clauses/where.h
- src/parser/grammar.c
- src/parser/grammar.h
- src/parser/grammar.y
- src/parser/lex.yy.c
- src/query_executor.c
- src/util/skiplist.c
- src/util/skiplist.h
- src/value.c
- src/value.h
- tests/flow/test_imdb.py
- tests/unit/test_filter_tree.cpp
- tests/unit/test_index.cpp
- tests/unit/test_skiplist.cpp
This resolves #106 for WHERE clauses (I think ORDER clauses should be handled similarly, but in a separate PR).
The most significant change seen here is that now predicate nodes in the filter tree are always arithmetic expressions, rather than being constant values or different graph entities. This lets us support functions in filters (`WHERE ID(a) < 100`, `WHERE LEFT(a.title, 3) = 'The'`), as well as making filter comparisons more robust in general (`WHERE 2000 < a.year` now works, for example).
Instead of storing pointers to comparison routines on the predicate nodes, all comparisons are currently using a slightly-improved `SIValue_Compare`. I would like to improve this function soon, and start using a separate routine for ORDER clauses, as being orderable in Cypher is different than …
> Arithmetic function filters

- src/execution_plan/ops/op_produce_results.c
- src/parser/ast.c
GRAPH.QUERY G "RETURN 1+2"
would fail, we were expecting RETURN to be accommodate by a MATCH clause.
> return clause might be the only clause specified

- src/arithmetic/algebraic_expression.c
- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_node_by_label_scan.c
- src/execution_plan/optimizations/optimizer.c
- src/graph/node.c
- src/graph/node.h
- src/graph/query_graph.c
- tests/flow/test_mix_labels.py
- tests/flow/test_multi_pattern.py
When a relation e.g. `knows` describes connection between several node types (Male and Female) then we must apply a type filter, consider `MATCH (s)-[:knows]->(t:Male) return s,t`
if we don't filter male nodes then `t` would include all nodes ever connected to by the `knows` relation, where we're only interested in a subset.
This will require some statistics over a relation, so we can re-enable commented optimisation.
> filter node type by multiplying label matrix

- src/execution_plan/optimizations/utilize_indices.c
This was a pretty straightforward bug! In building an index iterator, the index and iterator were not being set to NULL when we switched between scan operations.
> Fix scoping of index and iterator in execution plan optimization

- src/bulk_insert/bulk_insert.c
- src/bulk_insert/bulk_insert.h
- src/execution_plan/ops/op_all_node_scan.c
- src/module.c
- src/util/datablock/datablock_iterator.c
- src/util/datablock/datablock_iterator.h
This PR resolves a few bugs surrounding the handling of unlabeled nodes.
The `AllStore` schema is now updated to accurately describe the properties of unlabeled nodes during bulk inserts, so that a proper result set can be formed from a query like `MATCH (a) RETURN a`.
Unlabeled nodes are not required to have attributes.
AllNodeScans can update node IDs like LabelScans.
Bulk inserts that generate errors do not enqueue multiple responses.
I think these are all useful fixes, and hopefully resolve the problems you encountered earlier, though the bulk syntax and token processing still seems quite fragile. We should discuss a deeper overhaul!
> Improve handling of unlabeled node bulk insertion

- docs/commands.md
- src/arithmetic/algebraic_expression.c
- src/parser/ast_common.c
- src/parser/ast_common.h
- src/parser/grammar.c
- src/parser/grammar.y
`()-[*4]->()
()-[*4..]->()
()-[*..4]->()`
All describe a fixed length edge of length 4, this PR fixed a wrong implementation which treated the above as a variable length path of sizes 1,2,3,4.
See docs section regarding variable length relations.
> fixed length edge

- src/bulk_insert/bulk_insert.c
- src/bulk_insert/bulk_insert_context.c
- src/graph/edge.c
- src/graph/graph.c
- src/graph/node.h
- src/module.c
Combined with the other leak PRs, this should resolve most if not all of the leaks in the bulk operation itself. Really, though, the leaks were not terribly significant - I estimate that DataBlock storage for the wiki dataset must take up a minimum of 4.15 gigabytes. =/
> Memory patches and node iterator fix

- Makefile
- src/Makefile
- src/valgrind.supp
- tests/Makefile
- tests/unit/Makefile
- tests/unit/unittests.supp
Run `make test_valgrind` to run all unit test files under Valgrind.
> Add test_valgrind command to Makefile

- src/parser/grammar.c
- src/parser/grammar.y
- src/parser/lex.yy.c
- src/parser/lexer.l
These changes _seem_ like safe improvements given the testing I've done, but they are still not sufficient to resolve all of the leaks in the token parsing itself.
> Improved memory management in query parser

- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op.c
- src/execution_plan/ops/op_all_node_scan.c
- src/execution_plan/ops/op_produce_results.c
- src/graph/query_graph.c
- src/graph/query_graph.h
- src/module.c
- src/resultset/resultset.c
- tests/unit/test_algebraic_expression.cpp
These are all pretty straightforward fixes to leaks I observed when comparing Valgrind results from sessions that issued single versus repeated queries.
> Fix leaks in memory scoped to individual queries

- src/filter_tree/filter_tree.c
- src/value.c
- src/value.h
There may be a more performant way to do this (the function could be replaced by a macro, and we could do some clever bit twiddling), but this has the benefit of readability!
This PR resolves a bug in the comparison of NULL values:
```
12:10 $ redis-cli GRAPH.QUERY imdb "MATCH (a:actor) WHERE a.fakealias > 1000 RETURN a LIMIT 1"
1) 1) 1) "a.name"
2) "a.age"
2) 1) "Graham McTavish"
2) "57.000000"
2) 1) "Query internal execution time: 0.292120 milliseconds"
12:10 $ redis-cli GRAPH.QUERY imdb "MATCH (a:actor) WHERE a.fakealias < 1000 RETURN a LIMIT 1"
1) 1) 1) "a.name"
2) "a.age"
2) 1) "Query internal execution time: 1.606249 milliseconds"
```
> Filter tree comparisons are always false between disjoint types

- src/commands/cmd_query.c
This is a pretty minor change, but as we free the AST from `_MGraph_Query`, attempting to access it from the parent thread causes a race condition.
> Don't access AST from main query logic after dispatching thread

- deps/GraphBLAS/Makefile
- src/Makefile
I would have preferred a solution that restricted itself to our own Makefile, but could not manage to do so. ([This link](https://stackoverflow.com/questions/43858722/cmake-how-to-check-target-for-build) makes me think that such a fix would require us to bypass GraphBLAS's current Makefile, which I'd also prefer not to do.)
In any case, this change removes compilation of the dynamic library and the demo targets, which saves us a good amount of time in `make` and reduces console output.
> Add GraphBLAS Makefile target for static compilation only

- deps/GraphBLAS/CMakeLists.txt
- deps/GraphBLAS/Source/GB.h
- src/graph/graph.c
- src/graph/graph_entity.c
- src/util/arr.h
- src/util/datablock/datablock.c
- src/util/rmalloc.c
- src/util/rmalloc.h
- tests/unit/test_algebraic_expression.cpp
- tests/unit/test_all_paths.cpp
- tests/unit/test_arithmetic_expression.cpp
- tests/unit/test_datablock.cpp
- tests/unit/test_graph.cpp
- tests/unit/test_gxb_matrix_del.cpp
- tests/unit/test_index.cpp
- tests/unit/test_skiplist.cpp
- tests/unit/test_tuples_iter.cpp
This PR switches to Redis allocation handling for:
- All GraphBLAS calls
- Datablocks
- GraphEntity properties
- All `arr.h` allocations
- The `Graph` object and its members
A bit of profiling (using Massif and Redis's info commands) suggest that these changes capture the vast majority of long-term allocations in the module. Outside of `arr.h`-dependent allocations, most temporary memory (things scoped to individual queries) are not captured by these changes.
I'm not sure why, but the Redis command `MEMORY USAGE [key]` on any graph artifact reports exactly the same (very minor) usage as the master branch shows. `MEMORY STATS`, however, seems to reflect the size of the data set and the average number of bytes per key fairly accurately.
> Core rm mallocs

- src/commands/cmd_bulk_insert.c
Pretty self-explanatory, but it works fine! Inserting 28 million edges, my speedup was about 7-8%, which isn't amazing, but it should continue to grow as graphs get larger.
> Don't flush changes to matrices after bulk insert operations

- docs/commands.md
Related to [this discussion about improving docs for deleting a node](https://github.com/RedisLabsModules/redis-graph/issues/158#issuecomment-433639549).
I think -- given the way the docs are structured...it seemed to me to put it under the `GRAPH.DELETE` section....primarily because that is the first place I looked at to find out how to delete a node -- then I noticed it was a whole graph delete.  So, most people are going to look there, and having a minor note like this will help folks, I think.
> doc update to explain how to delete a node

- deps/GraphBLAS/Makefile
So far as I can tell, there is no good portable way to choose a good number of jobs for the `-j` flag to Makefiles. I'd still rather have it be _something_ other than 1, and 8 is my personal standard choice. This compiles GraphBLAS static in 45 seconds on my machine (against 167 seconds on the master branch).
> Build GraphBLAS with 8 jobs by default

- src/parser/ast.c
- tests/flow/test_multi_pattern.py
This PR was intended to resolve #172 by verifying that no MATCH entities appear in multiple patterns.
(This is a temporary solution, as ultimately we should be able to allow that behavior).
It has some additional logic to allow multiple references to entities within a pattern, because that should be fine.
However, these don't actually resolve properly right now:
```
16:54 $ redis-cli GRAPH.QUERY G "CREATE (a:l {val: 1})-[:e]->(:l {val:2})-[:e]->(a)"
1) (empty list or set)
2) 1) "Labels added: 1"
2) "Nodes created: 2"
3) "Properties set: 2"
4) "Relationships created: 2"
5) "Query internal execution time: 0.663885 milliseconds"
16:55 $ redis-cli GRAPH.QUERY G "MATCH (a)-[]->(a) RETURN a"
1) 1) 1) "a.val"
2) 1) "2.000000"
3) 1) "1.000000"
2) 1) "Query internal execution time: 0.547030 …
```
> Don't allow entities to be referenced by multiple match patterns

- Dockerfile
This _might_ resolve an issue @K-Jo reported with our Docker images:
```
➜  oss cat graph.js
#!/bin/sh
. version.properties
docker run --name redis-oss -d -p 6379:6379 redislabs/redisgraph:edge
➜  oss ./graph.js
1079a513da98c7dfae76a26ec24c3fe90211c1c899934a15463278f90a838039
➜  oss docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
➜  oss docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                     PORTS               NAMES
1079a513da98        redislabs/redisgraph:edge   "docker-entrypoint.s…"   10 seconds ago      Exited (1) 8 seconds ago                       redis-oss
➜  oss docker logs 1079a513da98
1:C 02 Nov 2018 22:03:03.427 # …
```
> Add OpenMP to Dockerfile dependencies

- src/commands/cmd_bulk_insert.c
- src/commands/cmd_delete.c
- src/graph/graph.c
- src/graph/serializers/serialize_graph.c
- src/stores/store.c
FLUSH commands will enter the Graph_Free routine without ever acquiring a lock, so I don't think it will ever be valid to unlock from that function. The only place we'd been relying on that was the GRAPH.DELETE operation, so I removed lock acquisition from there. It holds the GIL and removes the key, so I don't think it should be possible for there to be any races there.
I also moved the LabelStore allocations and frees (not including the triemaps') to use rmalloc.h. This is what they use in the serializer, so parity is important.
> Fixes around FLUSH logic

- src/graph/entities/edge.h
- src/graph/graph.c
- src/graph/serializers/serialize_graph.c
- src/graph/serializers/serialize_store.c
- tests/unit/test_graph.cpp
I believe that the changes to property store deserialization here will resolve issues MOD-114 and MOD-115. `RedisModule_LoadStringBuffer` does not null-terminate strings; rather, it stores the length along with the byte sequence. We usually resolve this by serializing `strlen(x) + 1`, but that doesn't work in the context of triemaps, as they are not null-terminated by default either.
This has never proven to be an issue on my platform, so I can't be 100% certain about the fix, but the change introduced here resolved relevant Valgrind warnings.
I switched Graph deserialization to logic more similar to bulk ops, allocating to capacity and resizing/syncing at the end of the function.
Loading about 2.4 million nodes and 10 million edges, the reported time to load from RDB was 2.131 seconds. …
> Serializer updates

- src/commands/cmd_query.c
- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_create.c
- src/execution_plan/ops/op_delete.c
- src/execution_plan/ops/op_delete.h
- src/execution_plan/ops/op_node_by_label_scan.c
- src/execution_plan/ops/op_update.c
- src/execution_plan/ops/op_update.h
- src/graph/entities/edge.h
- src/graph/entities/node.h
- src/graph/graph.c
- src/graph/graph.h
- src/graph/graphcontext.c
- src/graph/graphcontext.h
- src/graph/serializers/graphcontext_type.c
- src/graph/serializers/serialize_graph.c
- src/index/index.c
- src/index/index.h
- src/stores/store.c
- src/stores/store.h
- src/util/arr.h
- src/util/skiplist.c
- src/util/triemap/triemap.c
- src/util/triemap/triemap.h
- tests/flow/test_index.py
- tests/flow/test_persistency.py
- tests/unit/test_graph.cpp
LabelStore triemaps now hold pointers to indices when available.
CREATE, SET, and DELETE operations appropriately modify indices.
> GA index updates

- src/commands/cmd_bulk_insert.c
- src/commands/cmd_delete.c
- src/commands/cmd_explain.c
- src/commands/cmd_query.c
This PR is currently for conversational purposes. If we think this is a required change, it must be added to `cmd_delete` and `cmd_bulk_insert`.
See RED-23856.
This is a rather interesting issue! When `RedisModule_BlockClient` is called from Lua or MULTI/EXEC, an error is queued and the internal `bc->client` is set to NULL. However, we can still call `RedisModule_GetThreadSafeContext` on that blocked client, which overwrites `bc->client` with a fake (non-connected) client.
The module actually performs perfectly normally, including keyspace updates, except the Redis-level replies no longer reach the user.
Should we consider this a Redis bug? The `unstable` branch exhibits the same behavior. Are we actually allowed to operate in non-blocking contexts, and just not reply?
> Don't execute queries from Lua or MULTI/EXEC blocks

- src/parser/grammar.c
- src/parser/grammar.y
- tests/Makefile
- tests/flow/test_multi_pattern.py
- tests/tck/features/AggregationAcceptance.feature
- tests/tck/features/ReturnAcceptance.feature
- tests/tck/features/StartingPointAcceptance.feature
Enabled TCK add support for multiple CREATE clauses within a single query
`GRAPH.QUERY G "CREATE (:p),(:x) CREATE (:x)-[:z]->({c:1})"`
> multiple CREATE clauses, enable TCK

- src/arithmetic/agg_funcs.c
- src/filter_tree/filter_tree.c
- src/resultset/resultset.c
- src/resultset/resultset_record.c
- src/value.c
- src/value.h
- tests/flow/test_value_comparisons.py
This PR resolves all the issues I could think of with respect to comparability and ordering, but I admit that it does so because I reversed my thinking on what the strcmp-style return should be for disjoint types again. I'm really pretty sure this matches that format.
I've wanted to separate comparability and orderability logic for a while, so this PR still seems worthwhile.
> Respect Cypher specifications for orderability and comparability

- src/graph/graph.c
Similar to what we're doing with create node
> entity returned from datablock should have its internals cleared

- src/util/skiplist.c
This fixes a bug reported by Chris.
The IndexScan reset function (called for Cartesian product queries) would crash if an index were re-used with a lower bound, since the lower bound value was not being independently stored within the index iterator.
> Index now stores copy of lower bound to properly reset

- tests/unit/Makefile
- tests/unit/test_skiplist.cpp
This is a followup fix to unit tests for #289. That change had caused an attempt to free a stack variable in the unit test.
I've additionally modified our `make test` command so that errors like these will fail prominently:
```
Running main() from gtest_main.cc                                                                                                                                                                                                                                                                                    
[==========] Running 3 tests from 1 test case. …
```
> Skiplist broken test

- src/Makefile
Comparison to master:
dump.rdb - 1.8mbs
10,000 nodes
100,000 edges
After graph load:
`master`
```
used_memory:4983048
used_memory_human:4.75M
used_memory_rss:143843328
used_memory_rss_human:137.18M
used_memory_peak:16296328
used_memory_peak_human:15.54M
used_memory_peak_perc:30.58%
used_memory_overhead:836494
used_memory_startup:786792
used_memory_dataset:4146554
used_memory_dataset_perc:98.82%
total_system_memory:16782913536
total_system_memory_human:15.63G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:28.87
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0
```
`branch`
```
used_memory:38549192
used_memory_human:36.76M
used_memory_rss:141426688 …
```
> Fix GraphBLAS flags to use rm_malloc family

- src/graph/serializers/serialize_graph.c
- tests/flow/test_persistency.py
Not having this already was an oversight, and causes serialization failures for some of Ariel's test files (as the bulk loader now supports NULL properties).
As a sidenote, we can't compare directly against NULL values, which I think we need to resolve:
```
12:22 $ redis-cli GRAPH.QUERY G "MATCH (a {primaryName: 'Gary Rosen'}) return a.primaryProfession ORDER BY a.primaryProfession"
1) 1) 1) "a.primaryProfession"
2) 1) "actor"
3) 1) "actor"
4) 1) "producer"
5) 1) "producer"
6) 1) "writer"
7) 1) "NULL"
12:22 $ redis-cli GRAPH.QUERY G "MATCH (a {primaryName: 'Gary Rosen'}) WHERE a.primaryProfession = NULL return a.primaryProfession ORDER BY a.primaryProfession"
1) 1) 1) "a.primaryProfession"
12:22 $ redis-cli GRAPH.QUERY G "MATCH (a {primaryName: 'Gary Rosen'}) WHERE a.primaryProfession != …
```
> Allow serialization of NULL-valued properties

- demo/imdb/imdb_queries.py
Happy new year, we've all gotten older!
We can fix some of these dynamically rather than statically, though I think "sum and average age of the Straight Outta Compton cast" would be a bit of a challenge.
I personally think that this fix is fine for now, but let me know if you think we should approach this differently.
> Fix outdated expected ages in IMDB tests

- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_conditional_traverse.h
Now that the execution plan can handle multiple records, we moved from a filter vector representing traversal from a single node to a filter matrix, representing multiple source nodes from which we perform traversal. first test see a ~X3 speed up.
the point to note is the need to keep matrix multiplication sparse, this was the main reason we've used a filter vector, now with a filter matrix we keep it to a decent size: MX16 at max, in the future we might want to be smarter about its dimension.
> traverse multiple nodes concurrently

- src/commands/cmd_bulk_insert.c
- src/commands/cmd_explain.c
- src/commands/cmd_query.c
- src/commands/cmd_query.h
- src/graph/graphcontext.c
- src/graph/graphcontext.h
I observed that race condition in unblockClient argv freeing again.
This solution is admittedly a bit silly, but I'm really disinclined to trust `RedisModuleCtx`-scoped memory at this point!
> Store graph name string outside of Redis context

- Dockerfile
- src/Makefile
- tests/unit/Makefile
My testing suggests that this is a safe change to make, and it entirely removes the module's dependency on OpenMP / libgomp:
before:
```
root@ecde5f7447d1:/# ldd redisgraph.so
linux-vdso.so.1 (0x00007fff3b593000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f61a14cb000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f61a12ac000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f61a0ebb000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f61a0b1d000)
/lib64/ld-linux-x86-64.so.2 (0x00007f61a19d9000)
libgomp.so.1 => not found
```
after:
```
root@5a8fc1694f6a:/# ldd graph.so
linux-vdso.so.1 (0x00007ffe2fbed000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f18bc8d1000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f18bc6b2000) …
```
> Don't install or check for OpenMP

- src/arithmetic/arithmetic_expression.c
- src/execution_plan/ops/op_conditional_traverse.c
- src/value.c
- src/value.h
2 minor changes I have meant to make in this PR.
The addition change feels a little nitpicky, but it does resolve a rather improbable bug:
```
$ redis-cli GRAPH.QUERY G "MATCH (a) RETURN ID(a), ID(a) + 1"
1) 1) 1) "ID(a)"
2) "ID(a) + 1.000000"
2) 1) "0"
2) "4607182418800017408"
3) 1) "1"
2) "4607182418800017408"
4) 1) "2"
2) "4607182418800017408"
```
> Type-safe numeric addition

- src/commands/cmd_bulk_insert.c
- src/commands/cmd_context.c
- src/commands/cmd_context.h
- src/commands/cmd_delete.c
- src/commands/cmd_explain.c
- src/commands/cmd_query.c
- src/commands/cmd_query.h
- tests/flow/test_multi_exec.py
#333 
MULTI
GRAPH.QUERY G QUERY
GRAPH.QUERY G QUERY
GRAPH.QUERY G QUERY
EXEC
> support multi-exec

- demo/imdb/imdb_queries.py
- demo/social/social_queries.py
- src/arithmetic/aggregate.c
- src/arithmetic/arithmetic_expression.c
- src/execution_plan/ops/op_aggregate.c
- src/execution_plan/ops/op_aggregate.h
- src/grouping/group.c
- src/grouping/group_cache.c
- src/resultset/resultset.c
- tests/flow/test_bulk_insertion.py
- tests/flow/test_graph_merge.py
- tests/flow/test_multi_exec.py
- tests/flow/test_persistency.py
- tests/flow/test_value_comparisons.py
This is a quality-of-life PR for outputting better-sanitized result sets with Redis's RESP protocol.
Example:
`redis-cli GRAPH.QUERY G "CREATE (:a {strval: 'string_prop', doubleval: 7.3, nullval: NULL})"`
Before:
```
redis-cli GRAPH.QUERY G "MATCH (a) RETURN a, ID(a)"
1) 1) 1) "a.nullval"
2) "a.doubleval"
3) "a.strval"
4) "ID(a)"
2) 1) "NULL"
2) "7.300000"
3) "string_prop"
4) "0"
```
After:
```
redis-cli GRAPH.QUERY G "MATCH (a) RETURN a, ID(a)"
1) 1) 1) "a.nullval"
2) "a.doubleval"
3) "a.strval"
4) "ID(a)"
2) 1) (nil)
2) "7.3"
3) "string_prop"
4) (integer) 0
```
`(nil)` and `(integer)` are redis-cli builtins. Clients will use their native representations, such as NULL being `None` for `redis-py`.
This should help ameliorate the issues described in #354.
> RESP-formatted result sets

- src/commands/cmd_query.c
- src/parser/newast.c
- tests/flow/test_query_validation.py
Validations updated to pass the test suite, adding support for:
- Multiple MATCH clauses
- Aliases set in RETURN clauses
- Blocking interdependent paths (a limitation for us currently, not a Cypher constraint)
One validation still must be written that we don't currently have a test for:
`MATCH (n {name: v}) RETURN n`
This would previously fail in the parser with:
`Syntax error at offset 27 near 'v'`
> Libcypher parser validations

- demo/imdb/imdb_queries.py
- demo/social/social_queries.py
- src/arithmetic/agg_funcs.c
- src/arithmetic/arithmetic_expression.c
- src/execution_plan/record.c
- src/graph/entities/graph_entity.c
- src/graph/serializers/serialize_graph.c
- src/index/index.c
- src/parser/grammar.c
- src/parser/grammar.y
- src/parser/lex.yy.c
- src/parser/lexer.l
- src/parser/token.h
- src/resultset/resultset.c
- src/value.c
- src/value.h
- tests/flow/test_graph_merge.py
- tests/flow/test_persistency.py
- tests/flow/test_value_comparisons.py
- tests/tck/utils/assertions.py
- tests/unit/test_aggregate_functions.cpp
- tests/unit/test_arithmetic_expression.cpp
- tests/unit/test_record.cpp
Instead of converting integer tokens to SIValue doubles, they will now be SIValue longs (signed 8-byte integers).
The serialization routines for SIValues have been extended, but this does not break backwards compatibility.
One caveat regarding user experience: queries that formerly produced doubles may now produce longs, and the result sets will be smarter about representing integers.
I think that the `value.h` and `arithmetic_expression.h` comparison and arithmetic routines have potential for optimization, which is a point we should revisit later.
> Support 8-byte integers as a user type

- src/filter_tree/filter_tree.c
- tests/flow/test_value_comparisons.py
This was a kind of silly oversight:
```
$ redis-cli GRAPH.QUERY social "MATCH (p) WHERE p.name != 5 RETURN p"
1) (empty list or set)
2) 1) "Query internal execution time: 0.549209 milliseconds"
```
Fixed now!
> Disjoint types should pass inequality comparisons

- src/graph/serializers/graphcontext_type.h
An addendum to #357, since older versions of RedisGraph won't be able to load RDB files created after that change (users won't be able to downgrade).
The resulting failure text is:
`Failed loading Graph, RedisGraph version (10013) is not forward compatible.`
It might be more sensible to make this change as part of a version bump.
> Increment RDB encoding version

- src/resultset/resultset.c
This PR increases the precision of doubles in the result set from 6 significant digits to 15 (at which point numbers will be rounded and/or printed in scientific notation).
This resolves #377
> Result set prints doubles with up to 15 significant digits

- src/arithmetic/algebraic_expression.c
- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_conditional_traverse.h
`GRAPH.QUERY IMDB "MATCH (a:Actors{Name: 'Kevin Bacon'})-[d:ACTEDIN]->(m:Movies)<-[f:ACTEDIN]-(c:Actors) WHERE c.Name != a.Name return a.Name, m.primaryTitle, c.Name"`
The query will construct an algebraic expression with a transpose operand, we've used to perform the transpose using GraphBLAS descriptor, upon each multiplication (wasteful)
This PR updates algebraic expression evaluation logic by performing operand transpose only once.
Using the large IMDB dataset, the query above dropped from 216 seconds to 7 seconds, 30X.
> Transpose algebraic operand only once

- src/resultset/resultset.c
Format:
```
$ redis-cli GRAPH.QUERY imdb "MATCH (a) RETURN a LIMIT 1" --compact
1)  1) "name"
2) "age"
3) "title"
4) "year"
5) "votes"
6) "rating"
7) "genre"
8) "actor"
9) "movie"
10) "act"
2) 1) 1) "a"
2) 1) 1) (integer) 0
2) 1) (integer) 7
3) 1) 1) (integer) 0
2) (integer) 2
3) "Graham McTavish"
2) 1) (integer) 1
2) (integer) 3
3) (integer) 58
3) 1) "Query internal execution time: 0.539020 milliseconds"
```
> Compact replies send string map, header + records, then statistics

- src/commands/cmd_query.c
- src/parser/ast.c
- src/parser/ast.h
- src/resultset/resultset.c
- src/resultset/resultset.h
- src/resultset/resultset_formatters.h
- src/resultset/resultset_replycompact.c
- src/resultset/resultset_replyverbose.c
This is not as clean a solution as I'd like, but currently the only places to retrieve the data of entity types in the user query are from the individual AST clauses or from the QueryGraph.
Verbose format:
```
$ redis-cli GRAPH.QUERY social "MATCH (a)-[e:visited]->(b) RETURN a, e, b.name LIMIT 1"
1) 1) 1) "a"
2) "e"
3) "b.name"
2) 1) 1) 1) "id"
2) (integer) 0
2) 1) "labels"
2) 1) "person"
3) 1) "properties"
2) 1) 1) "name"
2) "Boaz Arad"
2) 1) "age"
2) (integer) 31
3) 1) "gender"
2) "male"
4) 1) "status"
2) "married"
2) 1) 1) "id"
2) (integer) 38
2) 1) "type"
2) "visited"
3) 1) "src_node"
2) (integer) 0
4) 1) "dest_node"
2) (integer) 16
5) 1) "properties"
2) 1) 1) "purpose"
2) "both"
3) "Amsterdam"
2) 1) "Query internal execution time: 26.699824 milliseconds"
```
Compact format:
```
$ …
```
> Include column's entity type in compact headers

- src/execution_plan/execution_plan.c
- src/execution_plan/execution_plan.h
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_node_by_id_seek.c
- src/execution_plan/ops/op_node_by_id_seek.h
- src/execution_plan/ops/ops.h
- src/execution_plan/optimizations/optimizations.h
- src/execution_plan/optimizations/optimizer.c
- src/execution_plan/optimizations/seek_by_id.c
- src/execution_plan/optimizations/seek_by_id.h
- src/util/datablock/datablock_iterator.h
- tests/flow/test_node_by_id.py
Seek graph entity by ID,
An optimisation which detects a search pattern similar to:
`MATCH (n) WHERE ID(n) = 5 RETURN n`
Will reduce a SCAN + FILTER operations into a single NODE_BY_ID_SEEK operation to quickly locate requested entity.
> node by id seek execution plan operation

- src/execution_plan/ops/op_cond_var_len_traverse.c
Fixes an issue in which a variable length traversal op attempts to free a Record during `CondVarLenTraverseConsume` that has already been freed in the op's Reset function (bug scoped to Cartesian product queries).
> #469 Fix double free of Record in variable length traverse

- src/execution_plan/ops/op_project.c
This is the only fix I found necessary after testing #518 by @DvirDukhan under Valgrind.
If aliases are provided, the fake record must be large enough to have them written back. This resolves memory errors in expressions like `RETURN 1+2 AS three` or the query
`MATCH (n:actor) RETURN count(n) as actors_count`
Which utilizes the count optimization to replace scans.
> Allocate space in fake record to accommodate aliases

- src/execution_plan/ops/op_project.c
fixed dummy record length in project op, as the first operator in the execution plan, for considering the anonymous entities.
> fixed dummy record length

- src/ast/ast.c
- src/ast/ast_validations.c
Improper use of triemap keys was causing the aggregation check to work improperly.
Before this fix:
```
127.0.0.1:6379> GRAPH.EXPLAIN social "MATCH (a) RETURN a.name, tolower(a.name), COUNT(a)"
1) "Results"
2) "    Project"
3) "        All Node Scan | (a)"
```
(Since `tolower` is longer than `COUNT`, on the second iteration the pointer contains the bytes `COUNTer`.) 
After:
```
127.0.0.1:6379> GRAPH.EXPLAIN social "MATCH (a) RETURN a.name, tolower(a.name), COUNT(a)"
1) "Results"
2) "    Aggregate"
3) "        All Node Scan | (a)"
```
> Fix function names for existence and aggregation checks

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression.h
- src/ast/ast_build_ar_exp.c
- src/execution_plan/ops/op_aggregate.c
- src/execution_plan/ops/op_project.c
- src/execution_plan/record.c
- src/execution_plan/record.h
- src/graph/entities/graph_entity.c
- src/index/index.c
- src/value.c
- src/value.h
- tests/unit/test_arithmetic_expression.cpp
This PR demonstrates the interface and treatment of memory ownership that I hope to adopt with respect to SIValues. It attempts to minimize redundant copying while making it clear at all points whether an access is potentially unsafe.
There are currently no memory errors in running the test suite and TCK with this approach (with malloc or jemalloc), but I suspect that there are some unplugged leaks on this branch that I'll continue to investigate.
Please comment or add questions as thoroughly as you would like! It's important for us all to agree with the approach we take to resolve this issue.
> Sivalue memory safety

- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_expand_into.c
- src/execution_plan/ops/op_expand_into.h
- src/execution_plan/optimizations/reduce_traversal.c
- src/filter_tree/filter_tree.c
Resolves #605 
Most of the changes in this PR just make `NewExpandIntoOp` more similar to `NewCondTraverseOp`.
The only important line is `op_expand_into.c:109`, which corrects a mis-assignment of the Record ID of ExpandInto's contained edge. The new logic is the same logic as seen in `NewCondTraverseOp`.
> Fix Record ID of edges held in ExpandInto op

- src/execution_plan/ops/op_apply.c
- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_create.c
- src/execution_plan/ops/op_merge.c
Update OpFree routines to work safely with the PropagateFree logic.
This fixes (at minimum) a possible crash in variable-length traversals. The crash occurred in the query:
```
MATCH (a)-[*]->(b)<-[*]-(c) MATCH (b)-[*]->(d) SET a.test = false, b.test = true, c.test = b.name
```
> All ops NULL-set variables in their free routines

- .circleci/config.yml
- src/Makefile
this PR restore the original makefile and executes the `strip` function at the circleCI build
> moved strip to circle flow

- src/value.c
this fixes a bug in SIArray_Compare function. There was a missing update which needed to be performed once a comparison which its return value is not 0 is executed.
> fixed a bug in SIArray_Compare function

- tests/tck/features/WithAcceptance.feature
- tests/tck/test_tck.py
- tests/tck/utils/graphs.py
This branch modifies the TCK "behave" test suit to use a single running environment. The environment is injected to the test suit before the test suit is executed. This fixes a bug in our execution where failed TCK scenarios where both marked as failed and pass.
> Changed tck tests to execute with single runtime environment

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/funcs.h
- src/ast/ast_build_ar_exp.c
- src/ast/ast_build_filter_tree.c
- src/ast/ast_shared.c
- src/ast/ast_shared.h
- src/ast/ast_validations.c
- src/ast/cypher_whitelist.c
- tests/tck/features/NullOperator.feature
- tests/tck/features/TernaryLogicAcceptance.feature
- tests/unit/test_arithmetic_expression.cpp
Added both IS NULL and IS NOT NULL unary operators to the arsenal. They can be used both as an expression the evaluate in RETURN clause, or as a leaf in a filter tree.
Added a test in test_arithmetic_expression.cpp
Enabled some TCK scenarios
Added a flow test for filter testing, since currently no TCK tests are enabled with those tests
> added IS NULL and IS NOT NULL unary operators

- src/ast/ast_validations.c
- tests/flow/test_graph_merge.py
- tests/tck/features/MergeRelationshipAcceptance.feature
This PR raises a validation error when a MERGE clause is preceded by a CREATE or MATCH clause, or more than 1 MERGE clause is present.
One current problem with OpMerge is that it doesn't differentiate between multiple streams.
2 TCK tests that are now skipped actually worked incorrectly:
```
gq G "CREATE (a:A), (b:B) CREATE (a)-[:TYPE {name: 'r1'}]->(b)"
gq G "MATCH (a:A), (b:B) MERGE (a)-[r:TYPE {name: 'r2'}]->(b) RETURN count(r)"
```
```
gq G "CREATE (a:A), (b:B)"
gq G "MATCH (a:A), (b:B) MERGE (a)-[r:TYPE {name: 'Lola'}]->(b) RETURN count(r)"
```
In both of these cases, we fail to resolve the pattern and create 2 erroneous nodes (the tests do not check for that side-effect).
5 other TCK tests that did pass appropriately are now disallowed, but I'd prefer to remove support this broadly …
> Disallow potentially unhandled MERGE queries

- src/ast/ast_validations.c
This PR introduces a quick fix for AST validation done over DELETE clause. The additional validation allows the DELETE to be called either after a match clause, or, after a projection. The critical part of the fix is that each delete expression is validated to be an identifier.
> hot fixed ast validation for DELETE. fixes #639

- deps/GraphBLAS/Makefile
- src/Makefile
This PR sets GraphBLAS `JOBS` build argument to be the maximal amount of logical CPU in the machine.
> set GraphBLAS jobs to the maximum of logical cpu

- deps/GraphBLAS/Makefile
- deps/GraphBLAS/README.md
- src/Makefile
I needed this change in order to compile locally.
(The README update was automated, I'm not sure why it didn't occur for you!)
> Don't override GraphBLAS C++ compiler

- Dockerfile
Added the `libomp-dev` dependency to docker file to support GraphBLAS 3.
> added libomp-dev to dockerfile

- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
Resolves #651 (as well as some slightly more complicated failures of the same type in WITH clauses).
> Fix referenced alias validations for WITH and WHERE clauses

- src/commands/cmd_delete.c
revert a change in cmd_delete to a previous version which adds the information about graph deletion instead just showing statistics.
> fix MOD331 - add graph deletion indication

- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_conditional_traverse.c
- tests/flow/test_relation_patterns.py
Resolves MOD-340
This PR fixes a bug in which conditional traversals over transposed edge matrices didn't determine the traversal direction properly if the edge matrix wasn't the first operand.
> Fix transpose logic for traversals with non-scan children

- src/execution_plan/optimizations/utilize_indices.c
This fix validates that the given filter tree for the utilize index optimization is not an expression (function), such that `_FilterTree_CollectAttributes` will not assert since it looking for only conditions or predicates.
> hot fix issue #667

- src/execution_plan/optimizations/reduce_count.c
- tests/flow/test_optimizations_plan.py
This PR fixes a crash that occurs when trying to apply the ReduceCount optimization to queries like:
`MATCH ()-[:know]->(r) RETURN COUNT(r)`
CondTraverse ops only store edge data if the traversed edge is referenced. In the above case, it is not, so we can't use the standard ReduceCount logic to get a count. The associated AlgebraicExpression only contains a boolean matrix, so checking its `nvals` would not correctly account for multiple edges connecting the same source and destination.
> Don't access undefined CondTraverse members

- src/arithmetic/arithmetic_expression.c
- tests/unit/test_arithmetic_expression.cpp
This PR modifies the `reduce` optimization of arithmetic expression, not to break once one of the arithmetic expression node children is not applicable to reduce. The optimization will try to reduce every child of the current arithmetic expression node.
> Fix arithmetic expression reduce

- src/execution_plan/optimizations/apply_join.c
- tests/flow/test_optimizations_plan.py
This PR resolves a regression in alias resolution when attempting to replace Cartesian Products with ValueHashJoin ops.
> Fix entity resolution in Value Hash Join insertions

- src/commands/cmd_bulk_insert.c
- src/commands/cmd_delete.c
- src/commands/cmd_explain.c
- src/commands/cmd_profile.c
- src/commands/cmd_query.c
- src/graph/graphcontext.c
- src/graph/graphcontext.h
- src/module.c
- tests/flow/test_graph_deletion.py
This PR creates a new empty graph for queries that should execute, even if the graph does not exist. This PR removes the need to create at least one node to execute a query.
This PR closes #666 as well as long-awaited behavioral enhancement.
> create graph if not exists

- src/commands/cmd_bulk_insert.c
- src/commands/cmd_context.c
- src/commands/cmd_context.h
- src/commands/cmd_delete.c
- src/commands/cmd_dispatcher.c
- src/commands/cmd_dispatcher.h
- src/commands/cmd_explain.c
- src/commands/cmd_explain.h
- src/commands/cmd_profile.c
- src/commands/cmd_profile.h
- src/commands/cmd_query.c
- src/commands/cmd_query.h
- src/commands/commands.h
- src/graph/graphcontext.c
- src/graph/graphcontext.h
- src/module.c
- tests/flow/test_multi_exec.py
As every query execution starts off on Redis main thread, we can acquire our graph context at that stage and avoid GIL locking at a later stage once we're executing on a different thread.
> avoid acquiring GIL

- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/graph/entities/edge.c
- src/graph/graph.c
- tests/flow/test_variable_length_traversals.py
The change in `cond_var_len_traverse.c ` is the actual fix here (good call, @DvirDukhan !), and the addition to `graph.c` is an additional downstream safeguard.
> Var len bugfix

- src/execution_plan/execution_plan.c
Small fix to AST variable in TLS after all ops are constructed (fixes invalid access in `RETURN *` column name building).
> Update AST in QueryCtx after segment construction

- src/ast/ast_validations.c
Introduces the validation fixes suggested in review on #717 .
Improved behavior includes:
```
"CREATE (a {v: fake()})"
(error) Unknown function 'fake'
"MATCH (a) WITH fake(a) AS e RETURN e"
(error) Unknown function 'fake'
"CREATE (a {v: COUNT(DISTINCT *)})"
(error) Cannot specify both DISTINCT and * in COUNT(DISTINCT *)
```
> Validate function calls in WITH and CREATE clauses

- src/ast/ast.c
- src/ast/ast.h
- src/ast/ast_validations.c
As a result of #719, this PR adds an AST validation for the existence of path patterns in a filter.  RedisGraph will reply with an error `RedisGraph currently does not support filtering with path pattern`, once path patterns exist in filter.
> added valdiation for path in filter

- src/execution_plan/optimizations/utilize_indices.c
- tests/flow/test_index_scans.py
Fix assertion error and invalid memory accesses described at https://github.com/RedisGraph/redisgraph-py/issues/57
> Index string ownership

- src/algorithms/dfs.c
- src/algorithms/longest_path.c
- src/arithmetic/algebraic_expression.c
- src/graph/query_graph.c
- src/graph/query_graph.h
- tests/unit/test_algebraic_expression.cpp
This PR improves on issue #738 , although there are still cases such as:
`MATCH (p1)-[c1:connected_to]->(p2),(p2)-[c2:connected_to]->(p3),(p3)-[c3:connected_to]->(p4),(p4)-[c4:connected_to]->(p1),(p1)-[c5:connected_to]->(p5),(p5)-[c6:connected_to]->(p6),(p6)-[c7:connected_to]->(p2),(p2)-[c8:connected_to]->(p7),(p7)-[c9:connected_to]->(p8),(p8)-[c10:connected_to]->(p6),(p6)-[c11:connected_to]->(p2),(p2)-[c12:connected_to]->(p3),(p3)-[c13:connected_to]->(p9),(p9)-[c14:connected_to]->(p7) WHERE 1=1 AND p1 <> p2 AND p1 <> p3 AND p1 <> p4 AND p1 <> p5 AND p1 <> p6 AND p1 <> p7 AND p1 <> p8 AND p1 <> p9 AND p2 <> p3 AND p2 <> p4 AND p2 <> p5 AND p2 <> p6 AND p2 <> p7 AND p2 <> p8 AND p2 <> p9 AND p3 <> p4 AND p3 <> p5 AND p3 <> p6 AND p3 <> p7 AND p3 <> p8 AND p3 <> p9 AND p4 <> p5 AND p4 <> p6 …
> check for node degree using original query graph

- deps/GraphBLAS/Makefile
- src/Makefile
Introduce updated `static_only` Makefile target, skip GraphBLAS demo compilation and resolve Docker build issues.
> Only build the graphblas_static target

- src/arithmetic/agg_funcs.c
- tests/flow/test_results.py
This PR solves the #767 server crash by adding default values to aggregation functions. Aggregation function should have a default value if every argument that it receives is invalid (null).
added flow test for aggregation functions default values.
> added default values for agg funcs

- src/graph/graph.c
- tests/flow/test_graph_deletion.py
this fixes performance issue #771. Modified `_BulkDeleteEdges` at `graph.c` to use graphBLAS operations instead iterative deletion of the edges.
Manually benchmarked against `master`: ±250ms vs 112466ms on master for deleting 50000 relations.
> changed bulk edge delete

- README.md
- ramp.yml
- src/commands/cmd_bulk_insert.c
- src/commands/cmd_context.c
- src/commands/cmd_context.h
- src/commands/cmd_dispatcher.c
- src/commands/cmd_explain.c
- src/commands/cmd_profile.c
- src/commands/cmd_query.c
- src/execution_plan/ops/op_create.c
- src/execution_plan/ops/op_delete.c
- src/execution_plan/ops/op_merge.c
- src/execution_plan/ops/op_update.c
- src/query_ctx.c
- src/query_ctx.h
- tests/flow/test_concurrent_query.py
this PR solves the preamble RDB issue.
for every write query the flow as follows:
```
LOCK GIL
Key open with `write` flag
Graph R/W lock with write flag
Commit changes in graph
Replicate verbatim
Unlock graph R/W lock
Close key
Unlock GIL
```
This PR also provides runtime exception mechanism in case of:
1. graph deletion during write query
2. graph replacement with other value during write query
> Module key access

- src/execution_plan/record.c
- tests/tck/features/AggregationAcceptance.feature
`UNWIND [42] AS props WITH props WHERE props > 32 WITH DISTINCT props AS p MERGE (a:A {num: p}) RETURN a.num AS prop`
> allow hashing of record with unknown entries

- src/ast/enrichment/annotate_projected_named_paths.c
- tests/tck/features/MatchAcceptance.feature
MATCH p = ()-[]->() WHERE length(p) = 1 RETURN p
@DvirDukhan we should improve `_annotate_projected_named_path`
By extracting all named path once for each AST segment.
> annotate named paths within match clause

- tests/tck/features/TriadicSelection.feature
These crashes were fixed by the OPTIONAL validation.
> Remove crash tags from OPTIONAL tests

- src/arithmetic/conditional_funcs/conditional_funcs.c
This PR fixes a double-free issue caused by `coalesce` invocation, over a `toString` function result value (`coalesce(toString(x))`).
The first free is called over the `coalesce` parameters array at `_AR_EXP_EvaluateFunctionCall` in the `cleanup` section where every intermediate result calculated by a nested function is freed. In this case, the result of `toString` was freed.
The second free was called from record free.
I changed `coalesce` to return a copy.
> coalesce now returns a copy

- src/module.c
- tests/flow/test_rename.py
this is a fix to PR #795 which handled the wrong type of event trigger, and missed a rename event. #795 was only validated against read-only queries, which do not execute additional keyspace manipulation, as opposed to write queries, so it missed the rename event. This PR is backed with write query test.
> fixed rename event handler. backed with test

- src/execution_plan/execution_plan.c
- tests/tck/features/VarLengthAcceptance.feature
This case is really so dumb that I'd have been willing to introduce a validation error instead, but we do properly handle somewhat more sensible cases like:
`MATCH (a)-[:LIKES*0]->()-[:LIKES]->(c)`
Adding support here is easier than adding a complex validation.
> Properly handle zero-hop traversals

- src/execution_plan/execution_plan.c
- src/execution_plan/execution_plan.h
- src/execution_plan/execution_plan_modify.c
- tests/flow/test_with_clause.py
- tests/tck/features/WithAcceptance.feature
This is a rather more complicated PR, but I think it was overdue - the old logic was very clunky!
The changes to `_ExecutionPlan_LocateReferences` are largely a logical refactor, though some changes there were necessary regardless.
The changes to where `_ExecutionPlan_PlaceFilterOps` is called are required to handle aliased WITH entities. Both of the following are valid:
```
UNWIND [1,2,3] AS a WITH a WHERE a = 1 RETURN a
UNWIND [1,2,3] AS a WITH a AS e WHERE e = 1 RETURN e
```
But previously we would crash on the second form. Now both work properly.
> Filter placement updates

- src/bulk_insert/bulk_insert.c
Pretty straightforward! The enum order is unchanged, so this is not a breaking change.
> Add support for long values in bulk loader

- src/Makefile
quick addition to ensure the compiler will store stack frame pointers during function calls  on DEBUG mode
> [add] ensure no-omit-frame-pointer on DEBUG mode

- src/execution_plan/optimizations/reduce_distinct.c
- tests/flow/test_optimizations_plan.py
Fix invalid removal of Distinct operations that are the child of an Aggregate op - this optimization is only valid when the Distinct operation is the _parent_ of the Aggregate. #863
> Only remove Distinct ops with an Aggregate child

- src/execution_plan/execution_plan_modify.c
- src/execution_plan/optimizations/apply_join.c
- tests/flow/test_optimizations_plan.py
before this fix: reducing cartesian product + filter to hash join only treated the first filter which both branches of the join are fully resolving as the join criteria.
after this fix: allow multiple filters which resolved by the same two branches of cartesian product to be appended after the hash join op.
> fixed issue #869. 

- src/execution_plan/execution_plan_modify.c
- tests/flow/test_optimizations_plan.py
Fix to crashing query with redundant filter in #869
> Preserve the children array order when replacing ops

- src/arithmetic/numeric_funcs/numeric_funcs.c
- src/value.c
- tests/flow/test_function_calls.py
Update the modulo function to accept floating-point arguments.
Required for the LDBC benchmark.
> Support float inputs for modulo computations

- src/ast/ast_build_reference_map.c
- tests/flow/test_path_filter.py
this PR fixes a crash caused by not referencing path filter entities 
queries like `MATCH (n) WHERE (n)-[:R {prop:1}]->() RETURN n` causes crash
> fixed ast mapping for path filter

- src/graph/graph.c
- src/graph/graph.h
- src/graph/serializers/encoder/encode_graph.c
- tests/flow/test_concurrent_query.py
- tests/unit/test_graph.cpp
This PR adds:
1. Mutex per matrix, which removed the entire graph mutex.
2. A temporary workaround for solving #890 by always locking the matrix. This solves a read-after-write dependency, which can be violated by the previous code at `graph.c`. The current state of our GraphBLAS extension methods is unaware if a matrix with pending updates did flush the updates or not. Currently, in `GB_Wait`, a matrix removes its`GB_Pending` object, before applying the changes it holds. This can expose an unstable state of the matrix during the execution of `GB_Wait`. On the one hand, the matrix is without pending changes. On the other hand, the pending changes are in progress or will be applied by `GB_Wait`. Our GxB method only checks if pending changes exist, and have no notion if they were flushed. …
> added mutex per matrix

- docs/commands.md
- src/procedures/proc_fulltext_query.c
- src/value.c
- tests/flow/test_procedures.py
> RediSearch query error reporting

- src/execution_plan/ops/op_aggregate.c
- src/execution_plan/ops/op_aggregate.h
- src/execution_plan/optimizations/reduce_count.c
This PR simplifies the logic in OpAggregate such that it will hopefully be easier to work with in the future. To some degree it also reduces the struct size, allocation count, and redundancy of OpAggregate, but the main benefit is really just clarity.
> Simplify OpAggregate logic, remove unnecessary struct members

- src/arithmetic/algebraic_expression/algebraic_expression.c
- src/arithmetic/algebraic_expression/utils.c
The function `_AlgebraicExpression_TransposeTranspose`, invoked by queries like:
`MATCH (b)-[rel:X]-(a) WHERE a.name = 'Andres' RETURN a`
Had a memory leak when replacing nodes in the expression tree.
This PR moves the responsibility for that free into `_AlgebraicExpression_InplaceRepurpose`.
> Always free emptied space on AlgebraicExpression replacement

- src/procedures/proc_fulltext_query.c
Fix memory leak on full-text index procedure calls that contain syntax errors, such as:
`CALL db.idx.fulltext.queryNodes('fruit', 'Orange || Apple') YIELD node RETURN node`
> Fix leak on full-text index queries with syntax error

- src/execution_plan/optimizations/utilize_indices.c
Resolves leak on (non-sensible) queries like:
`MATCH (p:person) WHERE p.age IN [] RETURN p.name`
> Fix leak on index scan IN optimization

- tests/flow/test_query_validation.py
Add flow test to validate the fix introduced in #944 .
> Add flow test to validate

- src/execution_plan/ops/op.c
- src/execution_plan/ops/op.h
- src/execution_plan/ops/op_project.c
- src/execution_plan/ops/op_project.h
- src/execution_plan/ops/op_update.c
This logic used to be here; it must have been accidentally deleted at some point.
Ensures that we can free all memory allocated for a Record in the event of a run-time error.
> Reintroduce logic for freeing memory on run-time errors

- src/graph/graph.c
Fixes memory leak on edge arrays (multiple edges of the same type connecting the same src-dest pair) upon graph/key deletion.
> Free internal edge arrays on relationship matrix deletion

- src/arithmetic/agg_funcs.c
- src/arithmetic/aggregate.c
- src/arithmetic/arithmetic_expression.c
- src/execution_plan/ops/op_cond_var_len_traverse.c
This PR fixes all memory leaks caused by the `collect()` function, and more broadly fixes leaks on aggregate function results and child expressions of aggregate AR_ExpNodes.
> Agg func fixes

- src/execution_plan/ops/op_project.c
I don't love this solution, but don't see a way to avoid it currently (see query in comment). I'd welcome alternative approaches!
> Fix leak on projected heap-allocated graph entities

- src/commands/cmd_dispatcher.c
- tests/flow/test_query_validation.py
Resolves issue causing enterprise QA failure.
> Validate arity per-command rather than globally

- src/arithmetic/algebraic_expression/algebraic_expression_construction.c
- src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
- tests/flow/test_bidirectional_traversals.py
- tests/flow/test_relation_patterns.py
- tests/unit/test_algebraic_expression.cpp
#1017 
We want to evaluate an expression where `transpose` operations are applied to operands,
this PR introduce an optimisation which pushes down transpose operations applied to other operation nodes, e.g. Add and Mul down to their individual operands.
```
Transpose(A + B) => Transpose(A) + Transpose(B)
Transpose(A * B) => Transpose(B) * Transpose(A)
```
> push down transpose operations

- src/arithmetic/arithmetic_expression.c
- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
- tests/tck/features/MiscellaneousErrorAcceptance.feature
Resolves #1061 and other missing checks for undefined variables.
The invalid access on undefined variable `bar` in the query:
`CREATE (:person{name:bar[1]})`
Now causes the error:
```
(error) bar not defined
```
Additionally, fixed an issue in which run-time errors are not propagated if encountered in nested evaluations.
> Better compile-time checking for undefined variables

- src/execution_plan/execution_plan_modify.c
- src/execution_plan/optimizations/reduce_scans.c
- src/execution_plan/optimizations/reduce_traversal.c
- tests/flow/test_null_handling.py
- tests/flow/test_optimizations_plan.py
- tests/tck/features/WithAcceptance.feature
Resolves #1068 
Added new exit case for `ExecutionPlan_BoundVariables` to only collect variables within the caller's scope. Updated the logic for optimizations that delete redundant scans and introduce ExpandInto ops only evaluate the appropriate scope.
> ReduceScan and ReduceTraversal respect variable scopes

- src/commands/cmd_delete.c
- src/commands/cmd_dispatcher.c
- src/graph/graphcontext.c
- tests/flow/test_keyspace_accesses.py
Fix crash when issuing graph commands to non-graph keys.
> Error properly on graph accesses of non-graph keys

- src/execution_plan/ops/op_node_by_label_scan.c
- tests/flow/test_path_filter.py
Resolves bug reported in #1083 
`NodeByLabelScanReset` resets the iterator, which is the correct behavior for the standard Consume routine. However, this causes `NodeByLabelScanConsumeFromChild` to either erroneously return a null record or crash following a reset.
The change here causes the iterator to be reset twice in a Reset->ConsumeFromChild sequence, which is redundant, but the alternative would be to have separate Reset routines for these two cases, which seems less preferable.
> LabelScan with child reads data correctly after reset

- src/ast/ast_build_filter_tree.c
- tests/unit/test_filter_tree.cpp
Should resolve #1088 
Fixes a bug in which multiple WHERE clauses allow a right-hand child to be added to a NOT condition. NOT is unary; this should never be allowed.
> Guarantee that NOT conditions are unary

- src/valgrind.supp
This will hopefully fix the intermittent automation failure in leak checking in test_persistency.py.
Sample failure: https://circleci.com/gh/RedisGraph/RedisGraph/6627
These reported leaks are the same currently as those currently suppressed in our valgrind.supp file, except the caller is the code that performs `DEBUG RELOAD`.
> Add suppression for erroneous leak reports after DEBUG RELOAD

- README.md
Paragraph on OSX build should read "CXX" instead of "CPP".
> Fixed compiler typo

- src/ast/ast_validations.c
- src/execution_plan/execution_plan.c
- tests/flow/test_union.py
Resolves #1046, fixing  the incorrect syntax error:
```
MATCH ()-[e]->() RETURN e UNION MATCH ()-[e]->() RETURN e"
(error) Cannot use the same relationship variable 'e' for multiple patterns.
```
Fixes a bug in OpDistinct logic on columns containing both nodes and edges (also, adds our first test for such columns!).
> Union bugfixes

- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_conditional_traverse.h
- src/execution_plan/ops/op_expand_into.c
- src/execution_plan/ops/op_expand_into.h
- src/execution_plan/ops/shared/traverse_functions.c
- src/execution_plan/ops/shared/traverse_functions.h
- src/execution_plan/optimizations/reduce_count.c
- tests/flow/test_bidirectional_traversals.py
- tests/tck/features/MatchingSelfRelationships.feature
- tests/tck/features/MergeRelationshipAcceptance.feature
- tests/tck/features/OptionalMatchAcceptance.feature
Resolves #1036, introduces shared logic for populating referenced edges in CondTraverse and ExpandInto operations.
> Bidirectional expand into

- src/ast/enrichment/annotate_params.c
- tests/flow/test_params.py
This PR skips AST enticement for missing parameters and leaves error reporting for run-time first access
#1091
> throw runtime-error on missing query parameters

- src/bulk_insert/bulk_insert.c
Minor update to bulk loader logic to skip invalid creation of NULL-valued properties, as this is not a valid Cypher construct.
> Skip NULL-valued properties in bulk loader

- src/arithmetic/algebraic_expression.h
- src/arithmetic/algebraic_expression/algebraic_expression.c
- src/arithmetic/algebraic_expression/algebraic_expression_eval.c
- src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
- src/arithmetic/algebraic_expression/utils.c
- src/arithmetic/algebraic_expression/utils.h
- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_conditional_traverse.h
- src/execution_plan/ops/op_expand_into.c
- src/execution_plan/ops/op_expand_into.h
- src/execution_plan/ops/shared/print_functions.c
- tests/Makefile
- tests/unit/test_algebraic_expression.cpp
As discussed in #1058, this PR reintroduces the optimization to transpose matrices that require it once rather than per-traversal. This greatly increases performance of dest->src traversals.
With this change, AlgebraicExpression trees will no longer have any transpose operation nodes after the optimization stage. As such, all the code paths that handle these operations are currently unused, but have largely been left as-is since they may prove useful again in the future.
> Perform one-time transpose of traversed matrices

- docs/configuration.md
- src/config.c
- src/config.h
- src/module.c
- src/module_event_handlers.c
- src/serializers/encoder/v7/encode_graph.c
Expose configuration for OpenMP max thread count on module load; add documentation for `THREAD_COUNT` and `OMP_THREAD_COUNT` configurations.
> Omp thread configuration

- src/graph/graph.c
Instead of sharing edge arrays when two nodes are connected by multiple edges of the same type, maintain two arrays. This solves a slowdown issue introduce by #877.
> Avoid flushing matrices by maintaining separate transpose edge arrays

- src/execution_plan/ops/op_index_scan.c
- src/execution_plan/ops/op_index_scan.h
- src/execution_plan/optimizations/utilize_indices.c
- tests/flow/test_index_scans.py
This PR resolves an issue with queries deadlocking if multiple Index Scans utilizing the same index are positioned in the op tree such that a write to that index cannot acquire the index's write lock, as in `MERGE (a:A {v: 1}) MERGE (b:A {v: 2})`:
```
1) "Merge"
2) "    Merge"
3) "        Index Scan | (a:A)"
4) "        MergeCreate"
5) "    Index Scan | (b:A)"
6) "        Argument"
7) "    MergeCreate"
8) "        Argument"
```
The solution is for index scans to build their iterator (and thus acquire their read lock) at the time of first `Consume` invocation, rather than at the time of op creation.
Resolves #1150
> Move index iterator construction to first Consume call

- docs/design.md
I followed your example with the latest `redislabs/redisgraph` docker image and got the error `Exactly one relationship type must be specified for CREATE`. 
This fixes the syntax.
> fix graph creation example

- src/ast/ast_validations.c
- tests/flow/test_params.py
- tests/flow/test_query_validation.py
`EXPLAIN` and `PROFILE` are cypher query execution options. In RedisGraph we have them as explicit commands.
This PR invalidate a query sent with those options as invalid query and prompts the user to use the explicit command 
```
127.0.0.1:6379> graph.query g "EXPLAIN MATCH (p:president)-[:born]->(:state {name:'Hawaii'}) RETURN p"
(error) The EXPLAIN option should be used in GRAPH.EXPLAIN command
127.0.0.1:6379> graph.query g "PROFILE MATCH (p:president)-[:born]->(:state {name:'Hawaii'}) RETURN p"
(error) The PROFILE option should be used in GRAPH.PROFILE command
```
closes #1181
> added explain and profile options as invalid options in redisgraph

- src/commands/cmd_query.c
- src/slow_log/slow_log.c
- src/slow_log/slow_log.h
> aggregated slowlog should maintain original timestamps

- src/valgrind.supp
(cherry picked from commit 386a8e6c8be9c59278c34c9ac8fd6cc6aac55c1e)
> Add suppression for erroneous leak reports after DEBUG RELOAD (#1094)

- src/execution_plan/ops/op_node_by_label_scan.c
- tests/flow/test_path_filter.py
(cherry picked from commit cce2ebb40143490a0e7c22a0e9eacdf6adf591bd)
> LabelScan with child reads data correctly after reset (#1086)

- src/commands/cmd_delete.c
- src/commands/cmd_dispatcher.c
- src/graph/graphcontext.c
- tests/flow/test_keyspace_accesses.py
* Error properly on graph accesses of non-graph keys
* Explicitly free QueryCtx on failed delete
* Update cmd_delete.c
(cherry picked from commit 0cf50df86d5846c1eba39b2c0fcf1f500c25abf2)
> Error properly on graph accesses of non-graph keys (#1069)

- src/execution_plan/execution_plan_modify.c
- src/execution_plan/optimizations/reduce_scans.c
- src/execution_plan/optimizations/reduce_traversal.c
- tests/flow/test_optimizations_plan.py
- tests/tck/features/WithAcceptance.feature
* ReduceScan and ReduceTraversal respect variable scopes
* Fix source lookup
* PR fixes
(cherry picked from commit 29b75d8bad41fa09edaec651c7093f53e18ee9c2)
> ReduceScan and ReduceTraversal respect variable scopes (#1070)

- src/arithmetic/arithmetic_expression.c
- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
- tests/tck/features/MiscellaneousErrorAcceptance.feature
* Improve AST validations to capture undefined variables
* Propagate errors in nested AR_EXP_Evaluate failures
(cherry picked from commit e62b8233e8368b4c2b2caa2df2205b102330711d)
> Better compile-time checking for undefined variables (#1063)

- src/execution_plan/ops/op_index_scan.c
- src/execution_plan/ops/op_index_scan.h
- src/execution_plan/optimizations/utilize_indices.c
- tests/flow/test_index_scans.py
* Move index iterator construction to first Consume call
* Address PR comments
(cherry picked from commit 78531537fd493f108a694272a4868d1afbe63cd7)
> Move index iterator construction to first Consume call (#1169)

- src/commands/cmd_query.c
- src/slow_log/slow_log.c
- src/slow_log/slow_log.h
(cherry picked from commit 5269402fecc2817e6e55c2a46e311eddc281b74f)
> aggregated slowlog should maintain original timestamps (#1199)

- src/arithmetic/arithmetic_expression.c
- src/ast/ast_build_op_contexts.c
- src/ast/ast_build_op_contexts.h
- src/ast/ast_shared.c
- src/ast/ast_shared.h
- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_merge.c
- src/execution_plan/ops/op_update.c
- src/execution_plan/ops/op_update.h
- src/graph/graph.h
- src/graph/graphcontext.c
- src/graph/graphcontext.h
- tests/unit/test_algebraic_expression.cpp
- tests/unit/test_filter_tree.cpp
- tests/unit/test_index.cpp
* Protect critical region of reading/updating GraphContext attributes
* Improve lock coverage
* Don't heap-alloc attribute ID values
* Change to QueryCtx lock check
* Bulk insert deadlock fix
* Remove FindOrAddAttribute calls from critical region
* Revert changes to QueryCtx
* Revert changes to Graph
* Introduce new rwlock for attribute mapping
* Only lookup property ID once
* Fix unit tests
* Fix possible duplicate entry
* Always retrieve attribute value in critical region
* Address PR comments
* Address PR comments
(cherry picked from commit d66affbf662090e298f6d8e7a475c71d809214b2)
> Resolve race in accessing/updating attribute maps (#1165)

- .astylerc
- .circleci/config.yml
- Dockerfile
- src/Makefile
- src/execution_plan/execution_plan.c
- src/execution_plan/ops/op_update.c
- src/execution_plan/ops/op_update.h
- src/graph/entities/node.h
- src/index/index.h
- src/schema/schema.c
```
git merge -X theirs master   
```
> Merge master to 2.2

- src/execution_plan/ops/op_value_hash_join.c
- tests/flow/test_null_handling.py
Resolves #1261 
NULL != NULL, so NULL join values should be discarded in ValueHashJoins.
> Ignore NULL values in ValueHashJoin

- src/algorithms/all_paths.c
- src/execution_plan/ops/op_all_node_scan.c
- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_cond_var_len_traverse.h
- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_conditional_traverse.h
- src/execution_plan/ops/op_create.c
- src/execution_plan/ops/op_expand_into.c
- src/execution_plan/ops/op_index_scan.c
- src/execution_plan/ops/op_merge_create.c
- src/execution_plan/ops/op_node_by_id_seek.c
- src/execution_plan/ops/op_node_by_label_scan.c
- src/execution_plan/ops/op_update.c
- src/execution_plan/ops/shared/create_functions.c
- src/graph/entities/node.c
- src/graph/entities/node.h
- src/graph/entities/qg_node.c
- src/graph/entities/qg_node.h
- src/graph/graph.c
- src/graph/query_graph.c
- src/index/index.c
- src/procedures/proc_fulltext_query.c
- src/procedures/proc_pagerank.c
- src/resultset/formatters/resultset_replycompact.c
- src/resultset/formatters/resultset_replyverbose.c
- tests/unit/test_bfs.cpp
- tests/unit/test_detect_cycle.cpp
- tests/unit/test_dfs.cpp
- tests/unit/test_query_graph.cpp
- tests/unit/test_traversal_ordering.cpp
Addresses #1248 and #1249 with respect to nodes.
Removes redundant lookups of node label data in the ResultSet formatters and OpUpdate, populates label data when possible in Scan and Traverse operations.
> Improve label logic

- src/execution_plan/ops/op_all_node_scan.c
- src/execution_plan/ops/op_merge.c
- src/graph/entities/edge.h
- src/graph/entities/graph_entity.h
- src/graph/entities/node.h
- src/graph/graph.c
- src/serializers/encoder/v7/encode_graph_entities.c
- src/serializers/graph_extensions.c
- src/util/datablock/datablock_iterator.c
- src/util/datablock/datablock_iterator.h
- tests/unit/test_datablock.cpp
- tests/unit/test_graph.cpp
- tests/unit/test_value.cpp
Move entity `id` from field from the `entity` struct, this structure is saved within the datablock, by doing so we can cut down on the amount of memory both node and edge require, the `id` is set in runtime whenever an entity is retrieved from the graph, entity's id is synced with the entity position with the datablock.
> migrate id from entity to both node and edge objects

- src/execution_plan/execution_plan_clone.c
- src/graph/query_graph.c
- src/graph/query_graph.h
- tests/flow/test_cache.py
this PR adds an update to query graphs stored in execution plan templates which contains unknown ids for labels or relationship types
the update happen only for those kinds of query graph before the template is cloned.
> updated query graph on template before clone

- src/execution_plan/optimizations/optimizer.c
- tests/flow/test_index_scans.py
This PR corrects the order in which optimizations are applied such that redundant scan ops are removed prior to promoting scan ops to index scans.
This is expected to resolve #1281.
> Remove redundant scan ops before applying index optimization

- src/execution_plan/ops/op_value_hash_join.c
Fixes a crash on the command:
```
GRAPH.PROFILE G "MATCH (a), (b) WHERE a.id = b.id MERGE (a)-[:rel]->(b)"
```
> Fix Profile endpoint crash on some ValueHashJoin queries

- .circleci/config.yml
`Opereto` been reverted to its older version, we're being asked to use the user/pass token.
> revert qa automation trigger

- src/Makefile
This PR address the issue #1243.
If this is only useful on macOS this flag need to be placed [here](https://github.com/RedisGraph/RedisGraph/blob/master/src/Makefile#L28).
> fix gcc-10 breaking changes

- src/execution_plan/execution_plan_reduce_to_apply.c
- tests/flow/test_path_filter.py
This PR changes the ExecutionPlan to which SemiApply branches and similar from the topmost plan to the plan that is bound to the op it is replacing.
This fixes the assertion failure observed in #1309 wherein `Record_Merge` did not accept that the SemiApply branch belonged to the same scope as the matching branch.
> Build apply ops in correct ExecutionPlan scope

- src/arithmetic/algebraic_expression.h
This is a strange fix to a Valgrind error that occurs on O3 compilation:
```
==11956== Conditional jump or move depends on uninitialised value(s)
==11956==    at 0x62D4BBA: _AlgebraicExpression_IsAdditionNode (algebraic_expression_optimization.c:17)
==11956==    by 0x62D4BBA: __AlgebraicExpression_MulOverAdd (algebraic_expression_optimization.c:60)
==11956==    by 0x62D4B69: __AlgebraicExpression_MulOverAdd (algebraic_expression_optimization.c:169)
==11956==    by 0x62D4B69: __AlgebraicExpression_MulOverAdd (algebraic_expression_optimization.c:169)
==11956==    by 0x62D57AF: _AlgebraicExpression_MulOverAdd (algebraic_expression_optimization.c:195)
==11956==    by 0x62D57AF: AlgebraicExpression_Optimize (algebraic_expression_optimization.c:532)
==11956==    by 0x62EB855: _traverse …
```
> Change struct member order to eliminate Valgrind complaint

- src/execution_plan/execution_plan.c
- tests/flow/test_query_validation.py
Issue #1313 showed that a wrong user query where they access to a property of a path, causes the graph to crash since it cannot find a suitable operation to locate the filter after it. Since paths are functions built or runtime, they cannot be treated as entities such as nodes and edges (properties map), since no operation is creating them (e.g. Modifies record mapping). Due to this reason, the execution plan is unable to find a suitable operation that declares on creating the path entities, and an assertion was triggered.
closes #1313
> moved assert to runtime error -  locate op suitable for a filter

- src/module_event_handlers.c
This is a straightforward deletion of the lock acquisition logic before forking. As writers that are modifying data will be holding the GIL, there is no danger of the server forking (due to bgsave or RediSearch garbage collection) while the graph is in an inconsistent state.
We do need to retain the `AfterForkChild` child handler, which allows `bgsave` children to avoid deadlocks by not accessing synchronization primitives.
> Forking no longer requires lock acquisition

- src/ast/ast.c
- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
This PR adds support for parsing results with multiple nodes. Closes #1329 
This exposes a bug in libcypher-parser:
For the query 
```
/* hum */ MATCH (:Test) // hum 
RETURN true // oi
```
The parsing result is (see last identifier)
```
@0   2..7   block_comment           /* hum */
@1  10..49  statement               body=@2
@2  10..49  > query                 clauses=[@3, @9]
@3  10..32  > > MATCH               pattern=@4
@4  16..23  > > > pattern           paths=[@5]
@5  16..23  > > > > pattern path    (@6)
@6  16..23  > > > > > node pattern  (:@7)
@7  17..22  > > > > > > label       :`Test`
@8  26..31  > > > line_comment      // hum 
@9  32..49  > > RETURN              projections=[@10]
@10  39..49  > > > projection        expression=@11, alias=@13
@11  39..43  > > > > TRUE
@12  46..49 …
```
> added leading comments for a query

- docs/commands.md
- src/RG.h
- src/procedures/proc_pagerank.c
- tests/flow/test_pagerank.py
> Pagerank empty matrix

- src/execution_plan/ops/op_node_by_label_scan.c
- tests/flow/test_cache.py
This PR updates the NodeScanCtx of op label scan during init time
If a label id is unknown during an execution plan template build time the label scan op's NodeScanCtx saves the label is as unkown. From this point forward, all the clones of this template will clone the id as unkown, even if it was created after the template was built (no label id resultion). This PR solves the label id resultion in op label scan initilization time.
Closes https://github.com/RedisGraph/JRedisGraph/issues/83
> added init time NodeScanCtx update on label scan

- src/arithmetic/algebraic_expression.h
- src/arithmetic/algebraic_expression/algebraic_expression.c
- src/arithmetic/algebraic_expression/algebraic_expression_construction.c
- src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
- src/arithmetic/algebraic_expression/utils.c
- src/arithmetic/algebraic_expression/utils.h
- src/execution_plan/execution_plan.c
- tests/flow/test_algebraic_expression_order.py
* Replace rightmost operand if traversing from dest->src
* Address PR comments
* rename nodes
* Address PR comments
* consider transpose when traversing expression
Co-authored-by: swilly22 <roi@redislabs.com>
(cherry picked from commit 770d257b3013a3fffae9fc117b229870e7e265ad)
> Replace rightmost operand if traversing from dest->src (#1295)

- src/serializers/decoders/current/v7/decode_graph.c
- tests/flow/test_v7_encode_decode.py
This PR resolves a potential inconsistency or segfault when loading graph keys from v7 RDB files by setting the GraphCtx within the QueryCtx for every deserialized key.
- In the test case, Graph A is encoded across 6 virtual keys, and Graph B is encoded using 1.
- We begin to load Graph A, but begin and finish loading Graph B before this is finished, triggering a [QueryCtxFree](https://github.com/RedisGraph/RedisGraph/blob/master/src/serializers/decoders/current/v7/decode_graph.c#L163).
- Subsequent keys loaded for Graph A [find the partially-populated GraphContext](https://github.com/RedisGraph/RedisGraph/blob/master/src/serializers/decoders/current/v7/decode_graph.c#L15), so do not update the QueryCtx.
- When we try to build Graph A's index, we [retrieve a null pointer for the …
> Always set GraphCtx in QueryCtx while decoding graph keys

- demo/client/prettytable/__init__.py
- deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c
- src/arithmetic/agg_funcs.c
- src/arithmetic/comprehension_funcs/comprehension_funcs.c
- src/datatypes/path/sipath.c
- src/execution_plan/execution_plan_build/execution_plan_modify.c
- src/serializers/graphcontext_type.c
- src/serializers/graphmeta_type.c
- src/util/arr.h
- src/util/datablock/datablock_iterator.c
Some small fixes due to LGTM alerts
> LGTM alert fixes

- src/arithmetic/conditional_funcs/conditional_funcs.c
- tests/flow/test_function_calls.py
This PR resolves an issue in which CASE...WHEN statements would directly copy SIValue outputs without first changing their ownership, which caused memory errors when the CASE expression evaluated to a heap-allocated result.
> Avoid double free of heap-allocated values in CASE...WHEN statements

- src/arithmetic/placeholder_funcs/placeholder_funcs.c
- src/execution_plan/execution_plan_build/build_match_op_tree.c
- src/execution_plan/execution_plan_build/reduce_to_apply.c
- tests/flow/test_optional_match.py
#1391 #1394
```
GRAPH.QUERY g "CREATE ()"
GRAPH.EXPLAIN g "MATCH (u) WITH u OPTIONAL MATCH ()--() WHERE (u)--() RETURN true"
GRAPH.QUERY g "MATCH (u) WITH u OPTIONAL MATCH ()--() WHERE (u)--() RETURN true"
```
```
GRAPH.EXPLAIN g "OPTIONAL MATCH (u) WHERE (u)-[]->() RETURN u"
```
> redundent filter construction and placement

- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
#1405
When performing query validations, we shouldn't treat procedure outputs as elements that need to be defined
Moreover there should be a follow-up PR that validates that procedure outputs haven't been previously defined, e.g.
`WITH 1 AS node CALL db.idx.fulltext.queryNodes('Movie', 'Book') YIELD node RETURN node`
and
`WITH 1 AS m CALL db.idx.fulltext.queryNodes('Movie', 'Book') YIELD node AS m RETURN m`
> query validation should not check if procedure outputs been defined

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression_construct.c
- src/arithmetic/boolean_funcs/boolean_funcs.c
- src/ast/ast_validations.c
- src/ast/cypher_whitelist.c
- src/errors.c
- src/errors.h
- src/execution_plan/execution_plan_build/execution_plan_construct.c
- src/execution_plan/execution_plan_build/execution_plan_construct.h
- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_unwind.c
- src/execution_plan/optimizations/compact_filters.c
- src/execution_plan/optimizations/optimize_cartesian_product.c
- tests/flow/test_optimizations_plan.py
- tests/flow/test_optional_match.py
- tests/flow/test_query_validation.py
- tests/flow/test_variable_length_traversals.py
This PR resolves a series of crashes identified by `CyphSem`, which can best be inferred by looking at the added tests.
The more significant changes include:
- Changing alias reference validations to be per-query rather than per-scope.
- Fix placement of constant filters (WHERE false) in OPTIONAL contexts.
- Add handling for NULL sources in variable-length traversals.
- Avoid memory errors when trying to clean up after UNWINDing an invalid list.
> Fuzzy test crashes

- src/arithmetic/arithmetic_expression.c
- src/arithmetic/arithmetic_expression.h
- src/ast/ast_build_filter_tree.c
- src/ast/ast_validations.c
- src/execution_plan/optimizations/compact_filters.c
- src/execution_plan/optimizations/optimize_cartesian_product.c
- src/filter_tree/filter_tree.c
- tests/flow/test_query_validation.py
- tests/unit/test_filter_tree.cpp
Refactor FilterTree conversion/validation logic, introducing compile-time errors for #1410 and other offending queries like:
```
MATCH (a) WHERE NOT NOT "" RETURN *
MATCH (u) where u.v NOT NULL RETURN u
```
Adds validation to ensure that the number of UNION clauses match the number of RETURN clauses, solving crashes in cases like:
```
CREATE (:L {v: 1}) UNION MERGE (:M {v: 2})
```
> Fuzzy test crashes 2

- src/value.c
Resolves #1434.
I don't think this is strictly necessary; I believe that these constructors for structs zero out all unspecified struct members. Nothing wrong with being explicit, though!
> Explicitly assign allocation type of SIValue primitives

- src/execution_plan/ops/op_merge.c
- tests/flow/test_graph_merge.py
This fix makes ON MATCH/CREATE SET behave the same as regular SET in the case of failed updates - https://github.com/RedisGraph/RedisGraph/blob/master/src/execution_plan/ops/op_update.c#L228-L231
> Don't assert on failed MERGE updates

- src/ast/ast_validations.c
- tests/flow/test_query_validation.py
Cypher allows traversal patterns to appear in a number of unexpected places, such as:
```
MATCH (a) RETURN (a)-[]->()
MATCH (a) RETURN a ORDER BY (a)-[]->()
MATCH (a {prop: ()-[]->()}) RETURN a
```
These constructions don't seem useful to me, and they often cause crashes because QueryGraph construction collects all paths in an AST:
https://github.com/RedisGraph/RedisGraph/blob/master/src/graph/query_graph.c#L301
This PR disallows all such constructions by introducing a whitelist of the AST nodes that can validly have traversals as their children.
Resolves #1428
> Disallow traversal patterns outside of the appropriate clauses

- docs/index.md
CPP is the environment variable for the preprocessor executable, CXX specifies the compiler path.
> Fixed bug in OSX build instructions

- src/execution_plan/ops/op_update.c
- tests/flow/test_index_updates.py
This PR resolves a bug in which, given a query like:
`MATCH (a) SET a.undindexed_prop = 5, b.indexed_prop = 10`
Both properties would be set to the indexed value of `10`.
This was triggered by assigning the unindexed property's ID to both updates when moving the indexed update to the first position.
> Fix replacement of unindexed prop when set before indexed prop

- src/schema/schema.c
- src/serializers/decoders/prev/v7/decode_graph_schema.c
In v2.0.19, the `IndexType` enum was extended with [IDX_ANY](https://github.com/RedisGraph/RedisGraph/blob/b16e1acfa88a41a936dcdcfee35feab28ffd23ac/src/index/index.h#L17). This should have been accompanied by an RDB version increase, as this enum is serialized and used to differentiate between exact and full-text indexes.
Since this did not happen, v7 RDBs may encode their types as `[IDX_EXACT_MATCH, IDX_FULLTEXT]` or `[IDX_ANY, IDX_EXACT_MATCH]`, depending on when they were created. This PR makes a partial fix to this problem by interpreting `IDX_ANY` in v7 as `IDX_EXACT_MATCH` - a perfect fix is impossible.
Since we have since incremented to v8 RDBs, this is not a problem newer RDB files can trigger.
Resolves #1472
> Decode IDX_ANY as an exact-match index

- docs/commands.md
- src/algorithms/LAGraph_bfs_pushpull.c
- src/arithmetic/algebraic_expression/algebraic_expression_optimization.c
- src/arithmetic/algebraic_expression/utils.c
- src/commands/cmd_config.c
- src/commands/cmd_config.h
- src/commands/commands.h
- src/config.c
- src/config.h
- src/execution_plan/ops/op_results.c
- src/execution_plan/ops/op_results.h
- src/graph/graph.c
- src/graph/graphcontext.c
- src/module.c
- src/module_event_handlers.c
- src/procedures/proc_bfs.c
- src/resultset/resultset.c
- src/resultset/resultset.h
- src/serializers/encoder/v8/encode_graph.c
- tests/flow/test_config.py
- tests/flow/test_results.py
Allow for result-set size limit to be configured, default is unlimited.
> configure resultset size limit

- src/execution_plan/ops/op_merge.c
- tests/flow/test_query_validation.py
Brings the logic of ON MATCH/CREATE SET into parity with SET and CREATE (changed in #1432).
The updated logic disallows the assignment of complex types like nodes to property values.
> Disallow assigning properties to complex types in MERGE SET

- docs/known_limitations.md
- src/execution_plan/ops/shared/create_functions.c
- src/graph/entities/graph_entity.c
- tests/flow/test_graph_create.py
- tests/flow/test_graph_merge.py
- tests/flow/test_query_validation.py
This PR resolves a bug in which the server crashes on attempting to access a property that is not yet created:
```
CREATE (a {val: 2})-[:E]->(b {val: a.val})
```
Unfortunately, with this fix the above query will still only set 1 property. While to my knowledge not formalized in Cypher, by convention both nodes should have `val` set to `2` by this query. That would require considerable redesigning, however, and the value add seems minimal.
This PR resolves #1492.
> Don't attempt to access non-existent properties

- src/arithmetic/arithmetic_expression_construct.c
- tests/flow/test_query_validation.py
Causes a compile-time error to be emitted when parameters refer to AST identifier nodes (unquoted strings).
Resolves #1502.
> Error on alias references in parameters

- src/arithmetic/algebraic_expression/algebraic_expression.c
- src/arithmetic/algebraic_expression/utils.c
- src/arithmetic/algebraic_expression/utils.h
- src/ast/ast_build_reference_map.c
- tests/unit/test_algebraic_expression.cpp
This PR fixes 2 misbehaviors:
The query:
```
MATCH (a)-[]-(:L{})<-[*0]-(b:L) RETURN a
```
Caused the server to crash.
The above query produced a different execution plan than the logically equivalent variant:
```
MATCH (a)-[]-(:L)<-[*0]-(b:L) RETURN a
```
(The second query does not have the empty property map.)
However, there are still problems evaluating 0-hop traversals. If the intermediate node does have filters, as in:
```
CREATE (:L {v:1})-[:E]->(:L {v: 2})<-[:E]-(:L {v: 3})
MATCH (a)-[]-(:L{v: 2})<-[*0]-(b:L) RETURN a
```
No results will be returned.
The difference can be seen in the execution plans:
```
redis-cli GRAPH.EXPLAIN G "MATCH (a)-[]-(:L)<-[*0]-(b:L) RETURN a"
1) "Results"
2) "    Project"
3) "        Conditional Traverse | (b:L)->(a)"
4) "            Node By Label Scan | …
```
> Fixes for zero-length traversals

- src/execution_plan/ops/op_index_scan.c
- tests/flow/test_cache.py
This PR resolves an issue in which reusing a cached execution plan after introducing a label and index can cause an invalid memory access on label schema lookup.
> Ensure label data is up-to-date when initializing index scans

- src/execution_plan/optimizations/utilize_indices.c
- tests/flow/test_index_scans.py
This PR resolves a regression caused by the fix https://github.com/RedisGraph/RedisGraph/pull/1440#discussion_r526646463 .
Filters of the form `val IN array` do not require normalization.
Resolves #1526
> Don't attempt to normalize IN filters when utilizing indexes

- src/execution_plan/ops/op_apply.c
Fixes an increase in memory consumption over time in OpApply. (Orphaned records are still ultimately freed in execution teardown.)
> Fix orphaned record in OpApply

- src/Makefile
Given we're passing `libcypher-parser` our `CFLAGS`, the default libcypher automake added optimization flag `-O2` is being overloaded with `-O0` ( given we don't pass one ). 
To validate this is the case, I've built current master with/without specifying an libcypher compiler optimization level -O3.
To test it I've ran memtier with a mixed reads/writes query pattern ( the queries we've been discussing this week ) and we've moved from 13.2K ops/sec with an p50 latency of 4.12ms ( including RTT ) to 14.3K ops/sec with an p50 latency of 3.83ms ( including RTT )
**without optimization ( O0 )**
```
1         Threads
50        Connections per thread
180       Seconds
ALL STATS
==========================================================================================================
Type …
```
> Enabled O3 compiler optimization on libcypher-parser ( we were overleading the default libcypher with O0 )

- src/arithmetic/arithmetic_expression_construct.c
- tests/flow/test_map.py
Support identifiers in map projections as in the following:
`MATCH (a) WITH a, a.prop AS p RETURN a {p}`
> Add support for raw identifiers in map projections

- src/arithmetic/arithmetic_expression_construct.c
This PR fixes a double free on the cached template of property lookups in a map projection:
```
RETURN n {.val1, .val2}
```
Previously the same variable operand `n` would be used for looking up the properties `val1` and `val2`, which would cause a double free on cache eviction.
> Create unique operand nodes for each property lookup in a map projection

- src/execution_plan/ops/op_create.c
- src/execution_plan/ops/op_update.c
- tests/flow/test_entity_update.py
- tests/flow/test_graph_create.py
```
UNWIND ['Vancouver','Portland','Calgary'] as city_name CREATE (:City{name: city_name})
MATCH (n) UNWIND ['Calgary'] as city_name SET n.name = city_name
```
In both queries the string was deleted before being set.
Generally speaking I think we should revisit our primitives memory management, as the current solution is a bit wasteful.
> persist and retain records in create or update scenarios

- src/execution_plan/ops/op_procedure_call.c
- src/graph/graphcontext.c
- src/procedures/proc_fulltext_create_index.c
- src/procedures/proc_fulltext_drop_index.c
- src/schema/schema.c
- tests/flow/test_index_create.py
- tests/flow/test_replication.py
> Lock on write proc

- src/Makefile
- src/ast/ast.c
- tests/flow/test_query_validation.py
Resolves erroneous query rejections due to buffer overflows.
#760 #1486
> Use file streaming endpoint to parse queries

- tests/benchmarks/updates_baseline.yml
…
Given we're still experimenting with the benchmarks CI KPI validation, this PR increases the `OverallClientLatencies.Total.q50` to be lower than 2.0 ( before was 1.5 ) so that we can collect further data and adjust afterwards...
> Updated benchmark UPDATE-BASELINE to be less restrictive in the latency KPI

- .circleci/config.yml
This PR:
- triggers CI benchmarks on nightly
- Avoids the failed "performance CI step" due to protective checks on forked PRs. example: https://app.circleci.com/pipelines/github/RedisGraph/RedisGraph/2388/workflows/106ab930-d930-4c71-a446-910216252e94/jobs/8960
> Triggering nightly CI benchmarks; Early return on CI benchmarks for forked PRs

- .circleci/config.yml
This PR fixes the issue caused on nightly CI benchmarks automation and the missing `CIRCLE_USERNAME`.
> Fixed missing github_actor on ci nightly benchmark automation

- src/resultset/resultset.c
- src/resultset/resultset.h
- tests/flow/test_timeout.py
Resolves #1585 
This PR additionally removes the behavior of emitting run-time errors as the last element of the result; they will instead be the entire result.
Old behavior:
```
GRAPH.QUERY G "MERGE (a {v: NULL}) RETURN a"
1) 1) "a"
2) (empty array)
3) (error) Cannot merge node using null property value
```
New behavior:
```
GRAPH.QUERY G "MERGE (a {v: NULL}) RETURN a"
(error) Cannot merge node using null property value
```
> Always report run-time errors as the sole reply

- src/graph/graphcontext.c
This PR solves a regression in which the attempted creation of pre-existing indexes currently does not mention indexes in execution statistics. This fix causes 0 indexes created to again be reported instead:
```
127.0.0.1:6379> GRAPH.QUERY G "CREATE INDEX ON :L(v)"
1) 1) "Indices created: 1"
2) "Cached execution: 0"
3) "Query internal execution time: 0.277525 milliseconds"
127.0.0.1:6379> GRAPH.QUERY G "CREATE INDEX ON :L(v)"
1) 1) "Indices created: 0"
2) "Cached execution: 0"
3) "Query internal execution time: 0.173453 milliseconds"
```
> Report 0 indices created on duplicate index creation

- tests/benchmarks/Readme.md
- tests/benchmarks/requirements.txt
This PR fixes:
```
https://app.circleci.com/pipelines/github/RedisGraph/RedisGraph/2632/workflows/b6bad16d-938c-4b60-960d-2a8b362c067f/jobs/9798
```
by skipping branch related automation when the branch info is not present ( on release )
> Fix: Updated benchmark utility. Update benchmark readme with newest specifications

- src/commands/cmd_bulk_insert.c
- tests/flow/test_bulk_insertion.py
This PR fixes a behavior introduced by #1596 in which 2 error messages are emitted instead of 1 (and an assertion fails). The problem occurs when a non-existent graph name is used in a GRAPH.BULK command that does not start with the BEGIN token.
> Emit a single error on failed GraphContext retrieval

- src/graph/entities/node.h
QueryGraph nodes can be cached with a label of `GRAPH_UNKNOWN_LABEL`, indicating that the relevant schema does not exist. When this schema is later created, the cache is not updated, resulting in the label ID being emitted as `-2`. This can be seen in the sequence:
```
$ redis-cli GRAPH.QUERY  G "MATCH (a:L)-[:E]->(b:L2) RETURN b" --compact
1) 1) 1) (integer) 1
2) "b"
2) (empty array)
3) 1) "Cached execution: 0"
2) "Query internal execution time: 0.601046 milliseconds"
$ redis-cli GRAPH.QUERY  G "CREATE (:L)-[:E]->(:L2)"
1) 1) "Labels added: 2"
2) "Nodes created: 2"
3) "Relationships created: 1"
4) "Cached execution: 0"
5) "Query internal execution time: 1.474727 milliseconds"
$ redis-cli GRAPH.QUERY  G "MATCH (a:L)-[:E]->(b:L2) RETURN b" --compact
1) 1) 1) (integer) 1
2) "b"
2) 1) 1) 1) …
```
> Fix label retrieval on cached unknown value

- src/module_event_handlers.c
- src/util/thpool/pools.c
- src/util/thpool/pools.h
- src/util/thpool/thpool.c
- tests/flow/test_stress.py
- tests/unit/test_thread_pools.cpp
Test:
As redis-benchmark keeps the server busy. e.g.
```
redis-benchmark -e GRAPH.QUERY g "UNWIND range (0, 1000000) AS x WITH x WHERE (x / 2) = 50  RETURN x"
```
issue a shutdown:
```
redis-cli shutdown
```
Due to the thread pools being destroyed one after another the `ThreadPools_GetThreadID` returns a wrong `thread id` as this relies on pool thread count, which leads to crash when performing `CommandCtx_UntrackCtx`
> drain thread pools before shutting down

- docs/configuration.md
- src/commands/cmd_context.c
- src/commands/cmd_dispatcher.c
- src/commands/execution_ctx.c
- src/config.c
- src/config.h
- src/errors.h
- src/util/thpool/pools.c
- src/util/thpool/pools.h
- src/util/thpool/thpool.c
- src/util/thpool/thpool.h
- tests/flow/test_pending_queries_limit.py
- tests/unit/test_thread_pools.cpp
limit the number of pending queries in the thread-pool, in case thread-pool internal queue size has reached the current configured limit and additional queries are received, these will get rejected with an error ("Max queries exceeded")
This is a load/runtime configuration,
to limit internal queue to 10 elements issue:`GRAPH.CONFIG set MAX_QUEUED_QUERIES 10`
> Limit threadpool queue size

- tests/benchmarks/requirements.txt
This PR fixes errors like the following (https://app.circleci.com/pipelines/github/RedisGraph/RedisGraph/2756/workflows/20ece276-b3f7-4018-947e-cda94d274ebc/jobs/10184) :
```
redisbench-admin: error: argument --github_branch: expected one argument
```
Given that depending on the CI trigger ( branch, version, nightly ) we have different CI env variables with/without github actor/ branch/ etc... The tool is now agnostic and handles those types of failures since v0.1.61:
https://github.com/RedisLabsModules/redisbench-admin/releases/tag/v0.1.61
> Fix CI benchmarks on version tag

- docs/datatypes.md
- src/ast/ast_validations.c
- src/execution_plan/execution_plan_build/build_projection_ops.c
- tests/tck/features/clauses/return/Return4.feature
- tests/tck/features/clauses/return/Return6.feature
Force user to specify aggregations within a separated WITH clause, this way determining which expressions take part in group key is clear to both user and RedisGraph.
`RETURN a, {b:x, c:count(n)}, d`
Will emit an error, instructing user to rewrite as:
`WITH key0, ..., count(n) AS c RETURN key0,... {b:x, c:c}`
> disallow aggregations in maps

- src/configuration/config.c
- tests/flow/test_config.py
This PR fixes a regression in which the `GRAPH.CONFIG GET *` command hangs indefinitely rather than correctly reporting results.
Resolves #1707
> Fix regression in GRAPH.CONFIG GET *

- src/execution_plan/execution_plan_build/build_match_op_tree.c
- src/execution_plan/execution_plan_build/build_merge_op_tree.c
- tests/flow/test_bound_variables.py
> ignore bound node when constructing a scan op for it

- .circleci/config.yml
This ensures that branches with certain names do not run CI step, given an explicit need to test. This brings this module in line with the others.
> early returns migrated to one place

- ramp.yml
- src/commands/cmd_config.c
- tests/flow/test_replication.py
After discussing this over with @MeirShpilraien, we've concluded:
1. GRAPH.CONFIG should not be considered as a write command
2. GRAPH.CONFIG should not be replicated
> Replicate graph config

- src/execution_plan/ops/op_merge.c
Fixes a bug in which the lock doesn't get released after `MergeCreate` builds entities, and is instead released in the force unlocking flow.
> Release lock after MergeCreate builds entities

- src/serializers/decoders/current/v9/decode_graph_entities.c
Datablock space for valid nodes and edges is allocated within `_InitGraphDataStructure`. Additional space is only required to accommodate deleted nodes and edges.
> Only allocate space for deleted nodes and edges

- src/ast/ast_build_op_contexts.c
- src/ast/ast_shared.c
- src/ast/ast_shared.h
- src/commands/cmd_explain.c
- src/commands/cmd_profile.c
- src/commands/cmd_query.c
- src/commands/execution_ctx.c
- src/commands/execution_ctx.h
- src/datatypes/map.c
- src/datatypes/map.h
- src/execution_plan/ops/shared/update_functions.c
- tests/flow/test_entity_update.py
This PR adds support for queries of the form:
```
CYPHER props={v2: 10} MATCH (n) SET n = $props
WITH {v1: True} as props MATCH (n) SET n += props
```
It additionally fixes a bug in which some user-level errors encountered during ExecutionPlan construction did not prevent the plan from being cached (and not throwing the error on cached executions).
Resolves #1730
> Support updating properties with map referenced by parameter or variable

- tests/benchmarks/entity_count.yml
The space in the test name is making the grafana redis datasource not behaving as expected ( making us unable to chart this use-case ). The solution is simple - rename the test so that it does not contain spaces.
> Fix edge_count.yml benchmark name.

- .circleci/config.yml
This PR should fix https://circleci.com/gh/RedisGraph/RedisGraph/11714?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
> [fix] Added missing common context to nightly perf automation

- src/algorithms/all_neighbors.c
The `levels` array of the `AllNeighborsCtx` is comprised of heap-allocated tuple iterators, which must be explicitly freed before the context is reused.
> Fix memory leak on AllNeighborsCtx_Reset

- deps/GraphBLAS/README.md
- deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c
- src/Makefile
- src/graph/graph.c
Extensive local testing suggests that this PR resolves #1785.
It appears that `GxB_set` or the particular matrix access it performs is not thread-safe, and can cause crashes when multiple new tuple iterators all attempt to set this field on the same matrix simultaneously.
This crash seemingly can only occur on the earliest set calls to `GxB_set`.
> Tuple iter race

- src/graph/graph.c
- src/graph/graph.h
- tests/benchmarks/implicit_edge_deletion.yml
This is a variant of #1793 that is compatible with GraphBLAS 3.2.0, which is used by RedisGraph 2.4.
It uses a different signature for `GxB_Matrix_export_HyperCSR` and a different call for ensuring that `Mask` is hypersparse.
> 2.4 Don't use bulk routine for implicit edge deletion <= 4

- src/Makefile
By default, do not exceed 8 jobs, so we don't OOM in CI.
Override (e.g. make JOBS=32) is possible.
> Build: allow specification of parallel jobs

- sbin/system-setup.py
Given that we don't use the man pages, but the make install target requires it, this ensures it won't break, and doesn't pollute the filesystem.  This is to fix the mac build, which cannot write to /usr/local/man.
> fixing peg to install man pages into local tree

- deps/GraphBLAS/Config/GraphBLAS.h.in
- deps/GraphBLAS/Include/GraphBLAS.h
- deps/GraphBLAS/README.md
- deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c
- src/algorithms/all_neighbors.c
- src/execution_plan/ops/op_cond_var_len_traverse.c
- src/execution_plan/ops/op_conditional_traverse.c
- src/execution_plan/ops/op_node_by_label_scan.c
- src/graph/graph.c
- src/graph/graph.h
- src/index/index.c
- src/procedures/proc_bfs.c
- src/serializers/encoder/v9/encode_graph_entities.c
- tests/unit/test_graph.cpp
- tests/unit/test_tuples_iter.cpp
When performing traversal on a reverse edge (Transpose) of type `R`
we might be inspecting `R` to get information such as dose `R` contains multiple edges, as a result if both `R` and `RT` contain pending changes we will be flushing both.
This PR make sure we inspect the traversed matrix, either `R` or `RT`
> support value extraction from tuple iterator

- src/execution_plan/execution_plan.c
- src/execution_plan/execution_plan_build/build_projection_ops.c
- src/execution_plan/ops/op_distinct.c
- src/execution_plan/ops/op_distinct.h
- tests/flow/test_distinct.py
- tests/flow/test_union.py
This PR resolves the bug reported in #1845 and additional misbehaviors in `OpDistinct`.
Previously, `OpDistinct` would extract the expressions to unique from its corresponding `OpProject` or `OpAggregate`. These expressions would include all `ORDER BY` expressions, which should _not_ be considered input to unique.
This had the additional effect of allowing expression lists to be mismatched in `UNION` queries, as `UNION` requires the same variables in the `RETURN` clause but is not affected by `ORDER BY` expressions. As such, if one of the subqueries had an `ORDER BY` and the other did not (or had different expressions), an assertion would fail.
Now `OpDistinct` accepts an explicit array of variables to unique. This is retrieved from the projection list in the case of explicit `DISTINCT` …
> OpDistinct does not unique ORDER BY expressions

- tests/benchmarks/variable_length_traversal.yml
Fixes the following failing perf ci due to wrong KPI constraints:
https://app.circleci.com/pipelines/github/RedisGraph/RedisGraph/3789/workflows/5e003090-bda0-4d76-a37e-1b9cdd94eef7/jobs/14038
Based on the current data:
we see that:
- a "safe" client p50 constraint KPI rule should be 70ms
- a "safe" lower limit for throughput can be 5 ops/sec 
- given the short duration of the benchmark it's better to extend it's total command issued parameter
> [fix] Adjusted VARIABLE_LENGTH_EXPAND_INTO KPIs

- src/serializers/encoder/v9/encode_graph_entities.c
- tests/flow/test_encode_decode.py
This PR resolves a serialization issue in which, after exhausting an adjacency matrix, the matrix tuple iterator was assigned to NULL.
This caused all further calls to the iterator to do no work, and the last edge of the previous matrix was repeatedly serialized until the edge count condition was satisified.
> Tuple iterator now updates properly when changing matrix to serialize

- src/ast/ast_validations.c
- tests/flow/test_entity_update.py
fix for https://github.com/RedisGraph/RedisGraph/issues/1891
> validate set items

- src/configuration/config.c
- tests/flow/test_config.py
Previously, GRAPH.CONFIG SET erroneously would not allow the timeout to be returned to 0 (unlimited), as it would only accept positive integers.
This PR removes that limitation by accepting any non-negative integer for the timeout value. It additionally resolves the same bug for `DELTA_MAX_PENDING_CHANGES` and `QUERY_MEM_CAPACITY`.
> Allow reconfiguring several configuration fields to 0 (default)

- src/ast/ast_validations.c
- tests/flow/test_params.py
> validate functions ref within params [WIP]

- src/algorithms/all_paths.c
- src/execution_plan/execution_plan_clone.c
- tests/flow/test_variable_length_traversals.py
This PR resolves a bug in which the AST segment scoped to each ExecutionPlan segment was only updated in thread-local storage upon instantiation in the clone routine. As such, if a subtree had a parent op describing AST 2, and 2 children respectively describing AST 1 and AST 2, the second child would inappropriately be linked to AST 1. This would cause crashes in queries like:
```
MATCH (a) WITH a OPTIONAL MATCH (a)-[e*]->(b) WHERE e.v = 5 RETURN a, b
```
Which produces the execution plan:
```
1) "Results"
2) "    Project"
3) "        Apply"
4) "            Project"
5) "                All Node Scan | (a)"
6) "            Optional"
7) "                Conditional Variable Length Traverse | (a)-[e*1..INF]->(b)"
8) "                    Argument"
```
The first AST segment only holds the …
> Update thread-local AST for every cloned op

- src/ast/ast_validations.c
- tests/flow/test_with_clause.py
This PR causes invalid references in a WITH...ORDER BY clause to be captured as compile-time errors rather than run-time errors, as in:
```
UNWIND [1,2,3] AS a WITH a ORDER BY nonexistent RETURN a
```
This has the effect of resolving #1863. A more concise query exhibiting the crash in this issue is:
```
CREATE (a:label9) WITH a ORDER BY node_0 MERGE path_2 = (node_0 {v: node_0.prop5})
```
This crash is caused by the invalid reference `node_0` causing the `MERGE` clause's `NodeByLabelScan` over `node_0` to erroneously be removed, and subsequently the `tie_segments` step of ExecutionPlan construction fails to link the two sub-ExecutionPlans. This crash is resolved by #1844.
> Aliases in WITH...ORDER BY must be valid references

- src/execution_plan/execution_plan.c
- src/execution_plan/execution_plan_build/build_match_op_tree.c
- src/graph/entities/qg_node.c
- src/graph/query_graph.c
- src/module_event_handlers.c
- tests/flow/test_persistency.py
- tests/flow/test_stress.py
#599
in case a readers is syncing a matrix while `BGSAVE` is called child process might inherit a lock matrix
this PR moves matrix sync to parent just before forking
> sync matrices on parent process before fork

- .circleci/config.yml
This PR extends the logic added in #1906 to additionally store logs generated while running the TCK.
> Store TCK server logs for CI runs

- tests/memcheck.sh
This PR modifies the memory-checking logic so that only the final heap summary is checked for leaks, not earlier summaries such as those triggered by `bgsave`.
Adding @rafie as a reviewer because of his talents at parsing Bash weirdness!
> Memcheck script only checks for server-process leaks

- demo/imdb/requirements.txt
- demo/social/requirements.txt
- src/commands/cmd_dispatcher.c
When module A calls a command of module B, B can't use blocked client.
> do not use block client if deny blocking is specified

- src/graph/rg_matrix/rg_new.c
- src/graph/rg_matrix/rg_resize.c
- tests/unit/test_rg_matrix.cpp
Luckily enough all of our matrices are squared...
> transposed delta matrix should be cols X rows

- src/arithmetic/arithmetic_expression.c
- src/ast/ast.c
- src/commands/cmd_bulk_insert.c
- src/graph/graphcontext.c
- src/query_ctx.c
- src/query_ctx.h
A `QueryCtx` struct can be instantiated by certain `OpFree` routines, such as the `QueryCtx_UnlockCommit` call at https://github.com/RedisGraph/RedisGraph/blob/master/src/execution_plan/ops/op_delete.c#L58. To avoid memory leaks, we should call `QueryCtx_Free` as part of the `GraphContext_Free` routine.
> Free thread-local data on graph deletion

- src/graph/graph.c
- src/graph/graph.h
- src/graph/graph_statistics.c
- src/graph/graph_statistics.h
- src/serializers/decoders/current/v9/decode_graph.c
- src/serializers/decoders/prev/v6/decode_graph.c
- src/serializers/decoders/prev/v7/decode_graph.c
- src/serializers/decoders/prev/v8/decode_graph.c
- src/serializers/graph_extensions.c
- tests/unit/test_graph.cpp
This PR augments the `GraphStatistics` struct to track node count per label, mirroring the logic that tracks edge count per relationship type.
> Track node count per label in graph statistics

- tests/flow/test_index_scans.py
- tests/flow/test_params.py
Tests fail due to issue described in https://github.com/RedisGraph/RedisGraph/pull/1950#issuecomment-922933659 .
> Use new param style when invoking redisgraph-py from tests

- .circleci/config.yml
- build/docker/Makefile
This updates the build to allow our control (even in parallel builds) of the edge/official push. Equally, this restores pushes to redisfab.
The rules now match the following dockerhub requirements
1. Push all tags to redisfab
2. Push versioned (i.e 1.2, edge, etc) tags to redislabs
a. **ONLY** push in the case where the OSNICK_OFFICIAL matches the OSNICK.
> Using the docker template system, and official releases

- .circleci/config.yml
As discussed with @gkorland, we will only enable the benchmark triggers on integration benchmarks.
> Running only performance CI on integration branches

- src/execution_plan/ops/op_procedure_call.c
- src/procedures/proc_bfs.c
- src/procedures/proc_bfs.h
- src/procedures/proc_ctx.h
- src/procedures/proc_fulltext_create_index.h
- src/procedures/proc_fulltext_drop_index.c
- src/procedures/proc_fulltext_drop_index.h
- src/procedures/proc_fulltext_query.c
- src/procedures/proc_fulltext_query.h
- src/procedures/proc_labels.c
- src/procedures/proc_labels.h
- src/procedures/proc_list_indexes.c
- src/procedures/proc_list_indexes.h
- src/procedures/proc_pagerank.c
- src/procedures/proc_pagerank.h
- src/procedures/proc_procedures.c
- src/procedures/proc_procedures.h
- src/procedures/proc_property_keys.c
- src/procedures/proc_property_keys.h
- src/procedures/proc_relations.c
- src/procedures/proc_relations.h
- src/procedures/procedure.c
- src/procedures/procedure.h
- src/procedures/procedures.h
- tests/flow/test_bfs.py
- tests/flow/test_procedures.py
Resolves #1701 
Previously, the default variable names for `YIELD` expressions were placed in the record map and any aliases applied to them were linked to them using `OpBase_AliasModifier`. This function increases the size of the record map without introducing new members, introducing empty spaces in the record, and should be avoided. Additionally, mapping the default variable names causes collisions when the same procedure is called twice in one query, in the case of `nodes` on the linked issue. This causes both aliases to be mapped to the first `nodes` output and the second BFS call to never have its outputs checked. This led to a double free when emitting results.
This PR also standardizes and simplifies the way procedures register their outputs. Non-yielded results are not computed, …
> Fix utilization of record offset in procedure calls, refactor outputs

- docs/commands.md
- src/execution_plan/ops/shared/update_functions.c
- tests/flow/test_entity_update.py
This PR allows graph entities to be used as right-hand values in `SET` clauses to perform attribute set assignment, as in:
```
MATCH (a {v: 1}), (b {v: 2}) SET a = b
```
Resolves #2045
> Allow copying of entity attribute sets in SET clauses

- src/commands/cmd_list.c
- src/resultset/formatters/resultset_replycompact.c
- src/resultset/formatters/resultset_replyverbose.c
- tests/flow/test_results.py
This PR replaces most instances of `RedisModule_ReplyWithSimpleString` calls with `RedisModule_ReplyWithStringBuffer` calls.
The former returns values of type `REDIS_REPLY_STATUS`, which cannot process the CRLF sequence (`\r\n`) and is generally meant for short status messages.
The latter returns `REDIS_REPLY_STRING` objects, which are binary-safe and can be up to 512 MBs.
Resolves #2072
> Use bulk string API for replying with strings

- docs/commands.md
- src/arithmetic/map_funcs/map_funcs.c
- src/datatypes/map.c
- src/datatypes/map.h
- src/graph/entities/graph_entity.c
- src/graph/entities/graph_entity.h
- tests/flow/test_function_calls.py
- tests/unit/test_map.cpp
This PR adds a `keys()` function that accepts map, node, and edge inputs and returns an array of all the keys the input contains.
Resolves #2098
> Add support for keys() function

- src/util/datablock/datablock.c
- tests/flow/test_node_by_id.py
Resolves #2119
Covered by: `tests/flow/test_node_by_id.py : test_for_none_existing_entity_ids`
> return NULL when trying to retrieve an out of bounds item

- src/execution_plan/execution_plan_build/execution_plan_modify.c
- tests/flow/test_optional_match.py
This PR resolves a bug that occurs when building an Optional subtree that updates its root to be a Filter op.
Previously, the `Argument` op was still associated with the master plan, so when updating its parent to be the new root, the master plan would incorrectly get rewritten instead of the plan generated for the Optional subtree.
> Bind Argument ops to the subplan they belong to

- src/arithmetic/conditional_funcs/conditional_funcs.c
- tests/flow/test_function_calls.py
This PR fixes an invalid assumption about SIValue memory scope in the `Distinct` function.
Resolves #2171
> Fix transfer of SIValue ownership in DISTINCT function

- commands.json
In [Redisinsight](https://github.com/RedisInsight/RedisInsight) we planning to support different syntaxes for code editor.
And in order to achieve this, we need to understand exactly where the other syntax is used
> Add "dsl" field for query arguments of commands

- src/commands/cmd_query.c
- src/graph/graphcontext.c
- src/util/thpool/pools.c
- src/util/thpool/pools.h
- tests/unit/test_thread_pools.cpp
When trying to add an async graph free job to the writers queue, the queue might be full (because of MAX_QUEUED_QUERIES configuration). This will cause the free job to be lost which will cause the graph to leak.
Added a force option to ThreadPools_AddWorkWriter so that the free jobs will not be lost.
@swilly22 I am not sure if this is the correct fix and if there are any other things to consider, please let me know what you think.
> Fix leak when MAX_QUEUED_QUERIES is used.

- src/module_event_handlers.c
On flushall, Graphs were freed twice:
1. On flush events handler
2. When the graph key was deleted by Redis
This caused invalid memory accesses on the second free, and on rare cases it caused crashes.
Avoid free the graphs on the flush event, free it only when the key is deleted by Redis.
> Fix invalid memory access after free.

- src/ast/ast_rewrite_star_projections.c
- tests/flow/test_star_projections.py
Fixes a bug in which `WITH *` clauses would have any `WHERE` filters lost.
Resolves #2206
> Properly clone WHERE predicates in WITH * projections

- .circleci/config.yml
This PR enables a CI profiler setup with the same specs as the default benchmark setups. 
It attaches a profiler for 60 seconds to each benchmark run and produces a set of outputs by default that can be consulted at 
[CI profiler viewer Grafana dashboard](https://benchmarksrediscom.grafana.net/d/uRPZar57k/ci-profiler-viewer?orgId=1):
- Flame Graph
- Main THREAD Flame Graph
- perf report per dso
- perf report per dso,sym
- perf report per dso,sym with callgraph
- perf report per dso,sym,srcline
- perf report per dso,sym,srcline with callgraph
- perf report top self-cpu
- perf report top self-cpu (dso=)
- Identical stacks collapsed
Note: the results produced with a profiler attached are not used on the visualizations/regression analysis due to the profiler overhead impact.
> Enabled CI profilers

- src/ast/ast.c
- src/ast/ast.h
- src/ast/ast_rewrite_star_projections.c
- src/ast/ast_rewrite_star_projections.h
- src/ast/ast_validations.c
- src/commands/execution_ctx.c
- tests/flow/test_query_validation.py
- tests/flow/test_star_projections.py
Error nodes exist at the clause level in libcypher-parser, which can make the clause index utilized by the `RETURN *` rewrite inaccurate.
This can simply be resolved by returning early if the clause index corresponds to an error node, as the query will immediately fail validation afterwards.
This issue can be seen in the sample query:
`MATCH (a)-[r:]->(b) RETURN *`
> Fix crash on parser errors in queries with RETURN *

- src/ast/ast_validations.c
- tests/flow/test_star_projections.py
Resolves an error in which queries of the form:
`MATCH (a) WITH * RETURN a`
erroneously would report the variable `a` as being undefined.
> Allow explicit variables to be returned after a WITH * projection

- src/serializers/decoders/current/v11/decode_graph.c
- src/serializers/decoders/current/v11/decode_graph_entities.c
- src/serializers/graph_extensions.c
this fix improve perf of loading an rdb of graph created with the below query
GRAPH.QUERY x "UNWIND range(1, 1000000) AS x CREATE (:N1), (:N2), (:N3), (:N4), (:N5)"
master: 22.541 seconds
this fix: 3.536 seconds
> improve the perf of matrix label population

- src/execution_plan/ops/op_node_by_label_scan.c
- tests/flow/test_graph_merge.py
This PR corrects a crash in which a LabelScan is freed by a write op such as Merge, then its members are subsequently accessed by a Reset call triggered by a Cartesian Product.
Resolves #1493
> Fix crash on accessing freed label scan member in Reset routine

- README.md
updated old URL 
https://oss.redislabs.com/redisgraph/result_structure
to
https://redis.io/docs/stack/graph/design/result_structure/
> updated redis CLI result format URL

- docs/docs/cypher_support.md
Parameters passed with a Cypher query were ended with a semicolon previously, see for instance https://github.com/RedisGraph/RedisGraph/issues/1078. Now this seems to return an error: 
```
127.0.0.1:6379> GRAPH.QUERY test "CYPHER name = \"opa\";  RETURN $name"
(error) Error: query with more than one statement is not supported.
```
This updates the documentation to reflect that. Or is this a code bug instead of a documentation being outdated bug, and the semicolon should still be accepted? I'm anxiously waiting for #1839, btw.
> Parameters list does not end with ; anymore

- .circleci/config.yml
Fixes for https://app.circleci.com/pipelines/github/RedisGraph/RedisGraph/6003/workflows/8418fc08-87f2-4d1a-a53a-643e5ea94d0d/jobs/23776
due to:
```
redisbench-admin run-remote \
--module_path $ROOT//root/project/src/$PACKAGE_NAME.so \
```
> Fixed nightly perf CI module path

- .circleci/config.yml
RedisGraph is the last of the modules to not build on Debian bullseye. This PR adds support via Circle - where we just add a new platform.
> Support for Debian Bullseye

- .circleci/config.yml
- tests/benchmarks/inspect_edges.yml
- Fixes: https://app.circleci.com/pipelines/github/RedisGraph/RedisGraph/7322/workflows/fefdca5c-d00a-45f7-b165-a883d811624e/jobs/30117
- Uses bullseye as the benchmark build image
- Updated benchmark runner OS from 18.04 to 20.04 ( https://github.com/RedisLabsModules/testing-infrastructure/pull/63 )
> Fixed the INSPECT-EDGES benchmark to achieave a feasible rps and latency for CI

- src/graph/query_graph.c
- tests/flow/test_graph_create.py
Hi, this PR is to fix #2643
The function _QueryGraphAddEdge() was modified to prevent add duplicated ids to edge->reltypeIDs array.
Tests were added in test_graph_create.py, please check if it is the correct file to add them.
> Fix Duplicate reports when matching relationship type :R|R

- tests/flow/test_encode_decode.py
- tests/flow/test_persistency.py
Previously there were failures while running the tests, usually in cases when the `redis-server` was installed via homebrew on macOS and/or it was impossible to configure it via the config file, and which (of course) wasn't built with the debug command being enabled by default. This enables the debug command when running the `redis-server`, so the tests will pass now.
> Enable running the tests by enabling debug command.

- src/arithmetic/entity_funcs/entity_funcs.c
- tests/flow/test_function_calls.py
This PR implements typeof(), #2729
It is a simple function which returns: ```SI_ConstStringVal(SIType_ToString(SI_TYPE(argv[0])));```
Sample output:
```
127.0.0.1:6379> GRAPH.QUERY g "CREATE (a:A {x:1, y:'1', z:true}) RETURN typeOf(a.x), typeOf(a.y), typeOf(a.z)"
1) 1) "typeOf(a.x)"
2) "typeOf(a.y)"
3) "typeOf(a.z)"
2) 1) 1) "Integer"
2) "String"
3) "Boolean"
```
```
127.0.0.1:6379> GRAPH.QUERY g "CREATE (a)-[b:B]->(c) RETURN typeOf(a), typeOf(b), typeOf(c)"
1) 1) "typeOf(a)"
2) "typeOf(b)"
3) "typeOf(c)"
2) 1) 1) "Node"
2) "Edge"
3) "Node"
```
> Implement typeof()

- src/arithmetic/entity_funcs/entity_funcs.c
- src/graph/graph.c
- src/graph/graph.h
- tests/flow/test_function_calls.py
#2753
`MATCH (a) RETURN outDegree(a), inDegree(a)` 
Previous implementation would extract `a's` incoming / outgoing edges into an array just to get its length and soon after discard it which is a waste. This new implementation doesn't extracts any edges but simply counts.
FYI with @AviAvni new design of NxM Relation matrices (N #nodes, M #edges) we get rid of Multi edge arrays and can simplify this change to a straight forward row reduction.
Quick benchmark:
Compute out degree of a node with 1M outgoing edges
```cypher
GRAPH.QUERY g "CREATE (a:A), (b:B)"
GRAPH.QUERY g "MATCH (a:A), (b:B) WITH a, b UNWIND range (0, 1000000) as x CREATE (a)-[:E]->(b)"
GRAPH.QUERY g "MATCH (a:A) RETURN outdegree(a)"
```
This PR 0.2ms
Current `Master` 20ms
100X improvement
> improved in out degree performance

- .circleci/config.yml
- .github/workflows/trigger-benchmark.yml
- @rafie before merging we need to ensure `CIRCLE_CI_SECRET` is present on repo
- @gkorland as discussed moving nightly of performance to once a week
> Updated circleci config to only trigger benchmark by label action:run-benchmark and to run performance nightly only once a week

- src/arithmetic/numeric_funcs/numeric_funcs.c
- tests/flow/test_function_calls.py
- tests/tck/features/expressions/typeConversion/TypeConversion2.feature
This PR is to fix bug #2794 
The function ```AR_TOINTEGER()``` was modified to include the conversion of ```T_BOOL``` types.
Tests for ```toInteger()``` and ```toIntegerOrNull()```were updated too.
The tck test ```[8] `toInteger()` failing on invalid arguments``` was skipped because bool type is invalid for it.
But maybe the tck test should be updated, because bool is not in the list of invalid types for ```tointeger()``` in [tck-M21](https://s3.amazonaws.com/artifacts.opencypher.org/M21/tck-M21.zip)
> Fix toInteger() and toIntegerOrNull() don't convert Booleans

- src/arithmetic/string_funcs/string_funcs.c
- tests/flow/test_function_calls.py
These changes are to fix bug #2798.
Changes:
- The validations of length are done before validating if input string is null
- Error message for invalid length was changed in functions ```left()```, ```right()```, and ```substring()```
Sample output:
```
127.0.0.1:6379> GRAPH.QUERY g "RETURN right('a', null)"
(error) length must be a non-negative integer
```
```
127.0.0.1:6379> GRAPH.QUERY g "RETURN right(null, null)"
1) 1) "right(null, null)"
2) 1) 1) (nil)
```
```
127.0.0.1:6379> GRAPH.QUERY g "RETURN right(null, -1)"
1) 1) "right(null, -1)"
2) 1) 1) (nil)
```
Edit: Sample output updated with changes  [f917b06](https://github.com/RedisGraph/RedisGraph/pull/2801/commits/f917b067e6a22abac5b75eea1060792c7461e114)
> Fix right(), left() length validation

- src/commands/cmd_dispatcher.c
fix https://github.com/RedisGraph/RedisGraph/issues/2809
> fix using timeout max as default when default not configured

- .circleci/config.yml
- tests/benchmarks/defaults.yml
Changes:
- Include internal/external latency ratio ( added to go benchmark took in https://github.com/RedisGraph/redisgraph-benchmark-go/pull/20 )
> Exporting the latency factor between internal and external latencies. Ensuring the factor is bellow 5

- src/util/cron.h
- tests/unit/test_cron.c
The test should have been flaky due to the time limit imposed with no control over the clock used as well as the scheduling.
This rewrites the test so that we don't rely on any clock rather than the real clock and for just the time out, not for "letting something happen". The test only proceeds when the cron thread has performed the job and notifies the main thread about its completion. This is made possible by using the file descriptors and the select system call.
The select also makes use of the time out facility and uses a three second time interval for the test timeout.
> Fix the flaky cron abort later test.

- src/util/num.c
- src/util/num.h
- tests/unit/test_num.c
For the initial stage, adds the number overflow additions. This is used by GRAPH.INFO when collecting information from multiple shards, as we can't guarantee the numbers we receive and add together won't overflow in the resulting integers.
> Add number utilities.

- commands.json
As #2748, which adds new commands without obeying [Semantic Versioning Specification (SemVer) - Item 2](https://semver.org/#spec-item-2), breaks redis.io :)
> Semver spec item 2 must be obeyed

- tests/benchmarks/batch_node_delete.yml
Benchmark batch node deletion, deleting 3,000 nodes in each batch. operating on a graph with 3M nodes.
> benchmark batch node deletion

- src/commands/cmd_constraint.c
This patch is to fix the maximum limit of properties used in GRAPH.CONSTRAINT.
The variable used is of type ``uint8_t``, then its range is ``0..255``
> GRAPH.CONSTRAINT: Fix validation max limit property count

- src/ast/ast_validations.c
- tests/flow/test_foreach.py
This PR handles the case `FOREACH(n in n | ...)`, which did not raise an error stating that `n` is undefined.
> Foreach fix

- src/arithmetic/arithmetic_expression_construct.c
- tests/flow/test_function_calls.py
This PR is to solve #2931, where wrong overflow error message are reported when string is converted to long integer.
The change just add ``errno = 0`` before ``strtol()``. 
Tests with valid an invalid queries were added also.
> Fix _AR_EXP_FromIntegerString()

- src/arithmetic/algebraic_expression/algebraic_expression_construction.c
- tests/flow/test_relation_patterns.py
This patch is to solve #3042
In the case of patterns where both nodes are shared, like ```(a)-[E0]->(b)<-[E1]-(a)```, the current ```_SharedNode()``` returns ``a``, but it should return ``b`` because the operations are being evaluated from left to right.
> Fix shared node detection

- tests/flow/test_bulk_insertion.py
- tests/flow/test_relation_patterns.py
This was the error reported by CI, when the ```ping_count``` is verified:
```sh
test_bulk_insertion:testGraphBulkInsertFlow.test09_large_bulk_insert
:x:  (FAIL):	1 > 1	test_bulk_insertion.py:394
```
The test ```test12_lt_zero_hop_traversals(self)``` was modified to use a local graph in its tests.
> Fix test_bulk_insertion

- src/execution_plan/ops/op.c
- tests/flow/test_index_delete.py
Fixes the `propagate_reset` mechanism to reset read operations before reseting write operations, in order to avoid writing on an indexed entity which is being read.
> fix propagate reset

- src/algorithms/all_neighbors.c
- src/algorithms/all_neighbors.h
- src/graph/rg_matrix/rg_matrix_iter.c
- tests/flow/random_graph.py
- tests/flow/test_function_calls.py
- tests/flow/test_variable_length_traversals.py
Deep DFS traversals performed a naive test to see if the current nodes is on the path, switch to hash table to track nodes on path
> Track visited nodes
